In [48]:
import pandas as pd

In [49]:
toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [50]:
toyota_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [ ]:
#Exrtacting a perticular column
model_series = toyota_data['car_model']

In [52]:

type(model_series)

pandas.Series

In [53]:
model_series.head()

0     Tundra
1     Tacoma
2    Corolla
3    Corolla
4     Tundra
Name: car_model, dtype: str

In [54]:
model_series.dtypes

In [55]:
model_series.index

RangeIndex(start=0, stop=5000, step=1)

In [56]:
#describe complete information of the data
model_series.describe()

count     5000
unique       6
top       RAV4
freq       860
Name: car_model, dtype: object

---

In [57]:
#List out Unique values
model_series.unique()

<StringArray>
['Tundra', 'Tacoma', 'Corolla', 'RAV4', 'Camry', 'Highlander']
Length: 6, dtype: str

In [58]:
#Returns the number of Unique values
model_series.nunique()

6

In [59]:
#Checks wheather the series are Null (True if Null | False if NotNull)
model_series.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: car_model, Length: 5000, dtype: bool

In [60]:
#.sum(),give the tital number of null vlaues
model_series.isnull().sum()

np.int64(0)

---

In [61]:
commision_per_series=toyota_data['commission_pct']

In [62]:
commision_per_series.isnull()

0       False
1        True
2        True
3        True
4       False
        ...
4995    False
4996    False
4997    False
4998     True
4999     True
Name: commission_pct, Length: 5000, dtype: bool

In [63]:
commision_per_series.isnull().sum()

np.int64(1274)

In [64]:
commision_per_series.notnull().sum()

np.int64(3726)

In [65]:
commision_per_series.describe()

count    3726.000000
mean        0.033725
std         0.012503
min         0.020000
25%         0.020000
50%         0.030000
75%         0.050000
max         0.050000
Name: commission_pct, dtype: float64

---

**Task**

Convert the string into Upper

In [66]:
model_series.head()

0     Tundra
1     Tacoma
2    Corolla
3    Corolla
4     Tundra
Name: car_model, dtype: str

In [67]:
model_series.str.upper()

0        TUNDRA
1        TACOMA
2       COROLLA
3       COROLLA
4        TUNDRA
         ...
4995    COROLLA
4996      CAMRY
4997     TACOMA
4998    COROLLA
4999     TUNDRA
Name: car_model, Length: 5000, dtype: str

---

**To get two column**

Note: 
* One column is a series
* More than one column is a DataFrame

In [68]:
sales_rep_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/sales_reps_data.csv")
sales_rep_data.head()

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active
3,4,Robert,Lopez,robert.lopez@toyota.com,-8631,11/21/20,South,Active
4,5,Steven,Wilson,steven.wilson@toyota.com,-6958,3/17/22,West,Active

In [69]:
sales_rep_data[["first_name","last_name"]]

     first_name  last_name
0       Anthony      Davis
1        Edward      Smith
2          Paul      Jones
3        Robert      Lopez
4        Steven     Wilson
5         Brian   Martinez
6   Christopher      Jones
7         David      Davis
8        Thomas      Smith
9   Christopher      Brown
10        David   Gonzalez
11       Daniel    Jackson
12       Robert  Hernandez
13       Daniel   Williams
14      William      Moore
15      Michael   Martinez
16      Charles      Lopez
17       Daniel   Martinez
18       Thomas     Wilson
19       Edward      Jones
20          Tom       Kyte
21        Scott      Tiger

In [70]:
sales_rep_data.describe()

          rep_id  phone_number
count  22.000000     22.000000
mean   11.500000  -6569.909091
std     6.493587   3083.091382
min     1.000000 -10733.000000
25%     6.250000  -9525.750000
50%    11.500000  -6520.500000
75%    16.750000  -4332.250000
max    22.000000  -1890.000000

In [71]:
sales_rep_data.isnull().sum()

rep_id          0
first_name      0
last_name       0
email           0
phone_number    0
hire_date       0
region          0
status          0
dtype: int64

In [73]:
toyota_data.isnull().sum()

sale_id              0
sale_rep_id          0
sale_date            0
car_model            0
sale_amount          0
commission_pct    1274
sale_status          0
dtype: int64

---

**Add new column by adding two column**

In [74]:
sales_rep_data.head(3)

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active

In [ ]:
#merge twu column (first_name & last_name)
sales_rep_data["full_name"] = sales_rep_data["first_name"]+" "+sales_rep_data["last_name"]

In [76]:
sales_rep_data.head(3)

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,full_name
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis
1,2,Edward,Smith,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith
2,3,Paul,Jones,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones

Note: 

* axis=0 → rows  ↓
* axis=1 → columns →

In [77]:
#deleting (first_name & last_name)
sales_rep_data.drop(['first_name', 'last_name'], axis =1)

,rep_id,email,phone_number,hire_date,region,status,full_name
0,1,anthony.davis@toyota.com,-5390,7/21/22,North,Active,Anthony Davis
1,2,edward.smith@toyota.com,-10708,12/24/19,North,Active,Edward Smith
2,3,paul.jones@toyota.com,-2301,9/6/22,East,Active,Paul Jones
3,4,robert.lopez@toyota.com,-8631,11/21/20,South,Active,Robert Lopez
4,5,steven.wilson@toyota.com,-6958,3/17/22,West,Active,Steven Wilson
5,6,brian.martinez@toyota.com,-8376,6/25/23,East,Active,Brian Martinez
6,7,christopher.jones@toyota.com,-1890,2/28/21,North,Active,Christopher Jones
7,8,david.davis@toyota.com,-6153,8/29/21,North,Active,David Davis
8,9,thomas.smith@toyota.com,-2623,4/2/22,West,Active,Thomas Smith
9,10,christopher.brown@toyota.com,-10635,8/15/20,North,Active,Christopher Brown
10,11,david.gonzalez@toyota.com,-3340,11/11/20,North,Active,David Gonzalez
11,12,daniel.jackson@toyota.com,-10733,8/22/22,West,Active,Daniel Jackson
12,13,robert.hernandez@toyota.com,-6888,7/26/23,North,Active,Robert Hernandez
13,14,daniel.williams@toyota.com,-9591,9/5/20,South,Active,Daniel Williams
14,15,william.moore@toyota.com,-4974,4/7/22,North,Active,William Moore
15,16,michael.martinez@toyota.com,-4289,4/3/22,East,Active,Michael Martinez
16,17,charles.lopez@toyota.com,-9619,5/11/20,West,Active,Charles Lopez
17,18,daniel.martinez@toyota.com,-2520,5/6/21,North,Active,Daniel Martinez
18,19,thomas.wilson@toyota.com,-4462,9/4/20,East,Active,Thomas Wilson
19,20,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,Edward Jones
20,21,tom.kyte@toyota.com,-10441,7/25/22,Unknown,Inactive,Tom Kyte
21,22,scott.tiger@toyota.com,-9330,3/23/22,Unknown,Inactive,Scott Tiger