## ".loc" (Lable-Based Indexing)

.loc is a label-based indexer in pandas. It allows us to select or modify specific rows and columns using their labels, and it's also commonly used for conditional filtering.

In [ ]:
import pandas as pd

# loading the data
toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")
sales_rep_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/sales_reps_data.csv")

In [14]:
#To get the rows based on the requirements usind index

toyota_selection = toyota_data.loc[5:9] #index 5 to 9
toyota_selection

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed
7,8,3,2024-11-05,Camry,25561.86,NaN,Completed
8,9,9,2024-11-25,RAV4,29690.54,0.03,Pending
9,10,14,2024-11-09,Camry,27321.71,0.03,Completed

In [15]:
# if we want perticular columns with required rows

toyota_selection = toyota_data.loc[5:9, ['sale_date', 'car_model', 'sale_amount']] 
toyota_selection

    sale_date car_model  sale_amount
5  2024-11-28      RAV4     34346.20
6  2024-11-30      RAV4     33073.24
7  2024-11-05     Camry     25561.86
8  2024-11-25      RAV4     29690.54
9  2024-11-09     Camry     27321.71

---

To get the amonunt greater than 30K

In [16]:
high_sales = toyota_data.loc[toyota_data['sale_amount'] > 30000]
high_sales

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed
...,...,...,...,...,...,...,...
4990,4991,20,2024-11-17,Highlander,36500.60,NaN,Completed
4992,4993,10,2024-11-26,Tundra,47497.87,0.02,Completed
4994,4995,12,2024-11-01,Tundra,41202.36,0.02,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,NaN,Cancelled

---

In [ ]:
#we can also do this without "loc"
toyota_data.loc[toyota_data['sale_amount'] > 30000]

#But we can't control over both rows and columns.
#Like: ['car_model', 'sale_amount', 'sale_date'] in the bolow example

To get the amonunt greater than 30K along with car_model, sale_amount, sale_date

In [ ]:

high_sales_model = toyota_data.loc[
    toyota_data['sale_amount'] > 30000, 
    ['car_model', 'sale_amount', 'sale_date']
]
high_sales_model

       car_model  sale_amount   sale_date
0         Tundra     44496.88  2024-11-18
1         Tacoma     34824.72  2024-11-08
4         Tundra     49811.99  2024-11-26
5           RAV4     34346.20  2024-11-28
6           RAV4     33073.24  2024-11-30
...          ...          ...         ...
4990  Highlander     36500.60  2024-11-17
4992      Tundra     47497.87  2024-11-26
4994      Tundra     41202.36  2024-11-01
4997      Tacoma     30780.39  2024-11-06
4999      Tundra     44525.85  2024-11-21

[2976 rows x 3 columns]

---

To get the amonunt greater than 30K and car_model is "RAV4"

In [ ]:
high_rava4_sales = toyota_data.loc[
    (toyota_data['sale_amount']> 3000) & (toyota_data["car_model"] == "RAV4"),
    # ()&()
    ['car_model', 'sale_amount', 'sale_date']
    ]

high_rava4_sales

     car_model  sale_amount   sale_date
5         RAV4     34346.20  2024-11-28
6         RAV4     33073.24  2024-11-30
8         RAV4     29690.54  2024-11-25
14        RAV4     28455.43  2024-11-14
17        RAV4     32751.81  2024-11-02
...        ...          ...         ...
4978      RAV4     27354.58  2024-11-30
4979      RAV4     30446.63  2024-11-21
4980      RAV4     30452.77  2024-11-01
4981      RAV4     28814.07  2024-11-23
4988      RAV4     31543.36  2024-11-04

[860 rows x 3 columns]

---

Convert all the "Null" values to "0"

In [32]:
toyota_data.loc[
    toyota_data["commission_pct"].isnull(),
    "commission_pct"
] = 0.0

In [33]:
toyota_data

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,0.00,Cancelled

---
---

# .iloc

“.iloc is a position-based indexer used to select rows and columns by their integer positions.”

In [ ]:
import pandas as pd

# loading the data
toyota_data_i = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")
sales_rep_data_i = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/sales_reps_data.csv")

In [3]:
toyota_data_i.head(3)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed

In [ ]:
toyota_data_i.iloc[0:3, 1:3] #(0:3 rows) , (1:3 columns)

   sale_rep_id   sale_date
0           16  2024-11-18
1           11  2024-11-08
2            5  2024-11-03

In [ ]:
toyota_data_i.iloc[3] #third

sale_id                    4
sale_rep_id               20
sale_date         2024-11-06
car_model            Corolla
sale_amount         20068.93
commission_pct           NaN
sale_status        Completed
Name: 3, dtype: object

In [12]:
#Select all rows and the first column.
toyota_data_i.iloc[:, 0]

0          1
1          2
2          3
3          4
4          5
        ...
4995    4996
4996    4997
4997    4998
4998    4999
4999    5000
Name: sale_id, Length: 5000, dtype: int64

---

Get highest sales and disply only the 5 rows

In [19]:
high_sale = toyota_data.loc[toyota_data['sale_amount'] > 30000]

In [20]:
high_sale.iloc[0:5, :]

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed

---

**Update the sale_rep_id 3rd row as 6**

In [25]:
toyota_data_i.iloc[2,1] = 6

In [ ]:
toyota_data_i.head(4)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,6,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed

In [30]:
toyota_data_i.iloc[2,3] = "Corolla"

In [31]:
toyota_data_i.head(4)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,6,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed

---
---

# Difference Between loc and iloc

* loc → selects data using labels/names.
* iloc → selects data using index positions (integer positions).

In [33]:
import pandas as pd

# loading the data
toyota_data_l_i = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")
sales_rep_data_l_i = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/sales_reps_data.csv")