**Use Case :If the tottal_commison is greater than 100, return True**

In [79]:
import pandas as pd
toyota_data = pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
    )

In [ ]:
#toyota_data.fillna({"commission_pct":0}, inplace=True)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,0.00,Cancelled

In [82]:
#calculate total_commision and remove null

def total_commision_calulation(sale):
    commission_pct = sale["commission_pct"] if pd.notnull(sale["commission_pct"]) else 0
    return sale["sale_amount"] * commission_pct

In [83]:
toyota_data.apply(total_commision_calulation, axis=1)

0       2224.8440
1          0.0000
2          0.0000
3          0.0000
4       1494.3597
          ...
4995    1074.2415
4996    1325.9620
4997     615.6078
4998       0.0000
4999       0.0000
Length: 5000, dtype: float64

`Or`

In [84]:
toyota_data["commisssion_total"] = toyota_data.apply(total_commision_calulation, axis=1)

In [85]:
def high(sale):
    return sale["commisssion_total"]>1000

In [86]:
toyota_data.apply(high, axis=1)

0        True
1       False
2       False
3       False
4        True
        ...
4995     True
4996     True
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [87]:
toyota_data["greates_than_1000"] = toyota_data.apply(high, axis=1)

In [88]:
toyota_data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commisssion_total,greates_than_1000
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.8440,True
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending,0.0000,False
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed,0.0000,False
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed,0.0000,False
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.3597,True

---