### **task 1:**
1. Display the first five rows.
2. Find the number of rows and columns.
3. Display the column names and data types.
4. Generate descriptive statistics.
5. Find the unique products, regions, and sale statuses.
6. Count the missing values in each column.
7. Identify duplicated records.
8. Count how many distinct sale IDs exist.

**Deliverable:** A short summary of the dataset's problems.

In [107]:
import pandas as pd

sales = pd.DataFrame({
    "sale_id": [101, 102, 103, 104, 105, 106, 107, 108, 108, 110, 111, 112],
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Laptop",
        "Laptop", "Monitor", "Mouse", "Keyboard"
    ],
    "region": [
        "North", "south", "East", "North",
        "West", "South", "east", "North",
        "North", "West", None, "East"
    ],
    "quantity": [2, 5, 3, 1, 2, 0, 4, 1, 1, 2, 3, 2],
    "price": [
        50000, 500, 1500, 50000,
        12000, 500, 1500, 50000,
        50000, 12000, 500, 1500
    ],
    "sale_date": [
        "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-08",
        "2026-01-09", "2026-01-10", "2026-01-11", "2026-01-12",
        "2026-01-12", "2026-01-13", "2026-01-14", "2026-01-15"
    ],
    "commission_pct": [
        0.05, 0.10, None, 0.05, 0.08, 0.10,
        0.06, 0.05, 0.05, None, 0.10, 0.06
    ],
    "sale_status": [
        "Completed", "Completed", "Pending", "Completed",
        "Completed", "Cancelled", "Completed", "Completed",
        "Completed", "Pending", "Completed", "Completed"
    ]
})

In [108]:
sales.head()

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status
0,101,Laptop,North,2,50000,2026-01-05,0.05,Completed
1,102,Mouse,south,5,500,2026-01-06,0.10,Completed
2,103,Keyboard,East,3,1500,2026-01-07,NaN,Pending
3,104,Laptop,North,1,50000,2026-01-08,0.05,Completed
4,105,Monitor,West,2,12000,2026-01-09,0.08,Completed

In [109]:
sales.shape

(12, 8)

In [110]:
sales.dtypes

sale_id             int64
product               str
region                str
quantity            int64
price               int64
sale_date             str
commission_pct    float64
sale_status           str
dtype: object

In [111]:
sales.describe()

          sale_id   quantity         price  commission_pct
count   12.000000  12.000000     12.000000       10.000000
mean   106.416667   2.166667  19166.666667        0.070000
std      3.553701   1.403459  23134.324492        0.022608
min    101.000000   0.000000    500.000000        0.050000
25%    103.750000   1.000000   1250.000000        0.050000
50%    106.500000   2.000000   6750.000000        0.060000
75%    108.500000   3.000000  50000.000000        0.095000
max    112.000000   5.000000  50000.000000        0.100000

In [112]:
sales["product"].unique()

<ArrowStringArray>
['Laptop', 'Mouse', 'Keyboard', 'Monitor']
Length: 4, dtype: str

In [113]:
sales["region"].unique()

<ArrowStringArray>
['North', 'south', 'East', 'West', 'South', 'east', nan]
Length: 7, dtype: str

In [114]:
sales["sale_status"].unique()

<ArrowStringArray>
['Completed', 'Pending', 'Cancelled']
Length: 3, dtype: str

In [115]:
sales.isnull().sum()

sale_id           0
product           0
region            1
quantity          0
price             0
sale_date         0
commission_pct    2
sale_status       0
dtype: int64

In [116]:
sales.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
dtype: bool

In [117]:
sales["sale_id"].nunique()

11

Deliverable:
1. sale_date is string instead of date_time
2. Region and commission_pct has null values
3. some data has duplicate values
4. sale_status can be categorized for memeory efficency

---

### **Stage 2 — Clean the data**🧹

Objective: Make the dataset more consistent and reliable.

Tasks:
1. Investigate duplicate sale IDs.
2. Decide how to handle duplicate records.
3. Check missing commission percentages.
4. Decide how to handle missing commission percentages and regions.
5. Standardize region names so that capitalization is consistent.
6. Check whether the data types are appropriate.
7. Convert the sale date column to a datetime type.
8. Decide whether records with zero quantity should be retained, removed, or analyzed separately.

In [118]:
sales.head()

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status
0,101,Laptop,North,2,50000,2026-01-05,0.05,Completed
1,102,Mouse,south,5,500,2026-01-06,0.10,Completed
2,103,Keyboard,East,3,1500,2026-01-07,NaN,Pending
3,104,Laptop,North,1,50000,2026-01-08,0.05,Completed
4,105,Monitor,West,2,12000,2026-01-09,0.08,Completed

In [119]:
sales[sales.duplicated()]

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status
8,108,Laptop,North,1,50000,2026-01-12,0.05,Completed

In [120]:
sales = sales.drop_duplicates(
    subset=["sale_id"]
)

In [121]:
sales.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
9     False
10    False
11    False
dtype: bool

In [122]:
sales.isnull().sum()

sale_id           0
product           0
region            1
quantity          0
price             0
sale_date         0
commission_pct    2
sale_status       0
dtype: int64

In [123]:
sales["region"] = sales["region"].fillna("Unknown")

In [124]:
sales.isnull().sum()

sale_id           0
product           0
region            0
quantity          0
price             0
sale_date         0
commission_pct    2
sale_status       0
dtype: int64

In [125]:
medain = sales["commission_pct"].median()

Note: Since the commission_pct is 0 even though the sale quantity is greater than 0, So appied median to missing commission_pct

In [126]:
sales["commission_pct"] = sales["commission_pct"].fillna(medain)

In [127]:
print(sales.isnull().sum())

sale_id           0
product           0
region            0
quantity          0
price             0
sale_date         0
commission_pct    0
sale_status       0
dtype: int64

In [128]:
sales["region"] = sales["region"].str.upper().str.strip()

In [129]:
sales

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed
2,103,Keyboard,EAST,3,1500,2026-01-07,0.06,Pending
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed
5,106,Mouse,SOUTH,0,500,2026-01-10,0.10,Cancelled
6,107,Keyboard,EAST,4,1500,2026-01-11,0.06,Completed
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed
9,110,Monitor,WEST,2,12000,2026-01-13,0.06,Pending
10,111,Mouse,UNKNOWN,3,500,2026-01-14,0.10,Completed
11,112,Keyboard,EAST,2,1500,2026-01-15,0.06,Completed

In [130]:
sales.dtypes

sale_id             int64
product               str
region                str
quantity            int64
price               int64
sale_date             str
commission_pct    float64
sale_status           str
dtype: object

In [131]:
sales["sale_date"] = pd.to_datetime(sales["sale_date"])

In [132]:
sales.dtypes

sale_id                    int64
product                      str
region                       str
quantity                   int64
price                      int64
sale_date         datetime64[us]
commission_pct           float64
sale_status                  str
dtype: object

In [202]:
cleaned_data = sales

---

### **Stage 3 — Filter and transform the data ⚙️**

Objective: Create useful columns and extract specific records.

Tasks:
1. Create a revenue column using price and quantity.
2. Create a commission_amount column.
3. Filter completed sales.
4. Find sales with revenue above ₹10,000.
5. Find records where commission percentage is missing.
6. Select only the columns needed for a sales report.
7. Sort sales by revenue, highest first.
8. Create a category column based on your own revenue thresholds.

In [134]:
sales["rev"] = sales["price"] * sales["quantity"]

In [135]:
sales.head()

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,rev
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500
2,103,Keyboard,EAST,3,1500,2026-01-07,0.06,Pending,4500
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000

In [136]:
sales = sales.rename(columns={"rev" : "revenue"})

In [137]:
sales["commission_amount"] = round(sales["revenue"] * sales["commission_pct"])

In [138]:
#Using Lambda and apply()
sales["commission_amount"] = sales.apply(lambda sale: round(sale["revenue"] * sale["commission_pct"]), axis=1)

In [139]:
sales.head()

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500,250
2,103,Keyboard,EAST,3,1500,2026-01-07,0.06,Pending,4500,270
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920

In [140]:
Completed_status = sales[sales["sale_status"] == "Completed"]

In [141]:
Completed_status

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500,250
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
6,107,Keyboard,EAST,4,1500,2026-01-11,0.06,Completed,6000,360
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
10,111,Mouse,UNKNOWN,3,500,2026-01-14,0.10,Completed,1500,150
11,112,Keyboard,EAST,2,1500,2026-01-15,0.06,Completed,3000,180

In [142]:
sales.iloc[sales["sale_status"] == "Completed"]

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500,250
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
6,107,Keyboard,EAST,4,1500,2026-01-11,0.06,Completed,6000,360
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
10,111,Mouse,UNKNOWN,3,500,2026-01-14,0.10,Completed,1500,150
11,112,Keyboard,EAST,2,1500,2026-01-15,0.06,Completed,3000,180

In [143]:
sales.query("sale_status == 'Completed'")

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
1,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500,250
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
6,107,Keyboard,EAST,4,1500,2026-01-11,0.06,Completed,6000,360
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
10,111,Mouse,UNKNOWN,3,500,2026-01-14,0.10,Completed,1500,150
11,112,Keyboard,EAST,2,1500,2026-01-15,0.06,Completed,3000,180

In [144]:
highest = sales[sales["revenue"] >= 10000]

In [145]:
highest

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
9,110,Monitor,WEST,2,12000,2026-01-13,0.06,Pending,24000,1440

In [146]:
sales.iloc[sales["revenue"]>= 10000]

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
9,110,Monitor,WEST,2,12000,2026-01-13,0.06,Pending,24000,1440

In [147]:
sales.query("revenue >= 10000")

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000
3,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920
7,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500
9,110,Monitor,WEST,2,12000,2026-01-13,0.06,Pending,24000,1440

In [148]:
sales.loc[sales["commission_pct"].isnull()]

Empty DataFrame
Columns: [sale_id, product, region, quantity, price, sale_date, commission_pct, sale_status, revenue, commission_amount]
Index: []

In [149]:
sales_report = sales[["sale_id", "product", "region", "quantity", "price", "commission_pct", "sale_status", "revenue", "commission_amount"]]

In [150]:
sales_report

,sale_id,product,region,quantity,price,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,0.05,Completed,100000,5000
1,102,Mouse,SOUTH,5,500,0.10,Completed,2500,250
2,103,Keyboard,EAST,3,1500,0.06,Pending,4500,270
3,104,Laptop,NORTH,1,50000,0.05,Completed,50000,2500
4,105,Monitor,WEST,2,12000,0.08,Completed,24000,1920
5,106,Mouse,SOUTH,0,500,0.10,Cancelled,0,0
6,107,Keyboard,EAST,4,1500,0.06,Completed,6000,360
7,108,Laptop,NORTH,1,50000,0.05,Completed,50000,2500
9,110,Monitor,WEST,2,12000,0.06,Pending,24000,1440
10,111,Mouse,UNKNOWN,3,500,0.10,Completed,1500,150
11,112,Keyboard,EAST,2,1500,0.06,Completed,3000,180

In [151]:
sales_report.sort_values(by="revenue", ascending=False)

,sale_id,product,region,quantity,price,commission_pct,sale_status,revenue,commission_amount
0,101,Laptop,NORTH,2,50000,0.05,Completed,100000,5000
7,108,Laptop,NORTH,1,50000,0.05,Completed,50000,2500
3,104,Laptop,NORTH,1,50000,0.05,Completed,50000,2500
9,110,Monitor,WEST,2,12000,0.06,Pending,24000,1440
4,105,Monitor,WEST,2,12000,0.08,Completed,24000,1920
6,107,Keyboard,EAST,4,1500,0.06,Completed,6000,360
2,103,Keyboard,EAST,3,1500,0.06,Pending,4500,270
11,112,Keyboard,EAST,2,1500,0.06,Completed,3000,180
1,102,Mouse,SOUTH,5,500,0.10,Completed,2500,250
10,111,Mouse,UNKNOWN,3,500,0.10,Completed,1500,150
5,106,Mouse,SOUTH,0,500,0.10,Cancelled,0,0

In [152]:
def category(sale):
    if sale["revenue"] < 8000:
        sale["category"] = "Low"

    elif sale["revenue"] >= 8000 and sale["revenue"] <= 15000:
        sale["category"] = "Medium"

    elif sale["revenue"] > 15000:
        sale["category"] = "High"

    return sale["category"]

In [153]:

sales_report["category"] = sales_report.apply(category, axis=1)

In [154]:
sales_report

,sale_id,product,region,quantity,price,commission_pct,sale_status,revenue,commission_amount,category
0,101,Laptop,NORTH,2,50000,0.05,Completed,100000,5000,High
1,102,Mouse,SOUTH,5,500,0.10,Completed,2500,250,Low
2,103,Keyboard,EAST,3,1500,0.06,Pending,4500,270,Low
3,104,Laptop,NORTH,1,50000,0.05,Completed,50000,2500,High
4,105,Monitor,WEST,2,12000,0.08,Completed,24000,1920,High
5,106,Mouse,SOUTH,0,500,0.10,Cancelled,0,0,Low
6,107,Keyboard,EAST,4,1500,0.06,Completed,6000,360,Low
7,108,Laptop,NORTH,1,50000,0.05,Completed,50000,2500,High
9,110,Monitor,WEST,2,12000,0.06,Pending,24000,1440,High
10,111,Mouse,UNKNOWN,3,500,0.10,Completed,1500,150,Low
11,112,Keyboard,EAST,2,1500,0.06,Completed,3000,180,Low

---

### Stage 4 — Calculate business metrics 📊

Objective: Answer questions a manager might ask.

Calculate:

1. Total revenue.
2. Total quantity sold.
3. Number of sales records.
4. Number of completed sales.
5. Number of cancelled sales.
6. Number of records with missing commission percentages.
7. Total revenue by product.
8. Total revenue by region.
9. Average revenue per sale by product.
10. Minimum and maximum sale revenue for each product.

Functions to revise:

groupby(), sum(), mean(), min(), max(), count(), agg(), reset_index().

Watch out: Distinguish between the number of records, total units sold, and total revenue. They measure different things.

In [155]:
sales_report

,sale_id,product,region,quantity,price,commission_pct,sale_status,revenue,commission_amount,category
0,101,Laptop,NORTH,2,50000,0.05,Completed,100000,5000,High
1,102,Mouse,SOUTH,5,500,0.10,Completed,2500,250,Low
2,103,Keyboard,EAST,3,1500,0.06,Pending,4500,270,Low
3,104,Laptop,NORTH,1,50000,0.05,Completed,50000,2500,High
4,105,Monitor,WEST,2,12000,0.08,Completed,24000,1920,High
5,106,Mouse,SOUTH,0,500,0.10,Cancelled,0,0,Low
6,107,Keyboard,EAST,4,1500,0.06,Completed,6000,360,Low
7,108,Laptop,NORTH,1,50000,0.05,Completed,50000,2500,High
9,110,Monitor,WEST,2,12000,0.06,Pending,24000,1440,High
10,111,Mouse,UNKNOWN,3,500,0.10,Completed,1500,150,Low
11,112,Keyboard,EAST,2,1500,0.06,Completed,3000,180,Low

In [156]:
#1
total_sales = sales_report["revenue"].sum()
print("Total Revenue: ",total_sales)

Total Revenue:  265500

In [157]:
#2
total_qty = sales_report["quantity"].sum()
print("Total quantity sold: ",total_qty)

Total quantity sold:  25

In [158]:
#3
No_of_sale_records = sales_report["sale_id"].count()
print("Number Of Sales are : ", No_of_sale_records)

Number Of Sales are :  11

In [159]:
#4
sales_canceled = sales_report.loc[sales_report["sale_status"] == "Cancelled"]

len(sales_canceled)

1

In [160]:
#6
missing_commision = sales_report.loc[sales_report["quantity"] == 0]
len(missing_commision)

1

In [161]:
missing_commision = (sales_report["quantity"] == 0).sum()
missing_commision

np.int64(1)

In [162]:
#7
total_revenue_per_product = (
    sales_report
    .groupby("product")["revenue"]
    .sum()
    .reset_index()
)
total_revenue_per_product

    product  revenue
0  Keyboard    13500
1    Laptop   200000
2   Monitor    48000
3     Mouse     4000

In [163]:
#8
total_revenue_by_region = sales_report.groupby("region")["revenue"].sum().reset_index()
total_revenue_by_region

    region  revenue
0     EAST    13500
1    NORTH   200000
2    SOUTH     2500
3  UNKNOWN     1500
4     WEST    48000

In [189]:
#9
avg_revenue_by_product = (
    sales.groupby("product")["revenue"]
    .mean()
    .reset_index()
)
avg_revenue_by_product

    product       revenue
0  Keyboard   4500.000000
1    Laptop  66666.666667
2   Monitor  24000.000000
3     Mouse   1333.333333

In [165]:
#10
sales_per_product = sales_report.groupby("product")["revenue"].agg(
    min_per_product = "min",
    max_per_product ="max",
    mean_per_product = "mean"

)

In [166]:
sales_per_product

          min_per_product  max_per_product  mean_per_product
product
Keyboard             3000             6000       4500.000000
Laptop              50000           100000      66666.666667
Monitor             24000            24000      24000.000000
Mouse                   0             2500       1333.333333

---

### **tasks 5:**
1. Merge the sales data with the representatives data using region.
2. Investigate any unmatched regions.
3. Calculate revenue by sales representative.
4. Compare each region's revenue against its target.
5. Create a summary table with total revenue and average sale revenue by region.
6. Reset the index if necessary to make the result a regular DataFrame.

Functions to revise:

pd.merge(), groupby(), agg(), query(), fillna(), assign(), reset_index().

Important: Check the assumptions behind the merge. A region name must match between the two DataFrames, and inconsistent capitalization can prevent a match.

In [167]:
reprensentatives = pd.DataFrame({
    "region": ["North","South","East","West"],
    "sales_rep":["Arun","Priya","Rahul","Meena"],
    "target":[120000, 80000, 60000, 100000]
})

In [168]:
reprensentatives["region"] = reprensentatives["region"].str.upper()

In [169]:
reprensentatives

  region sales_rep  target
0  NORTH      Arun  120000
1  SOUTH     Priya   80000
2   EAST     Rahul   60000
3   WEST     Meena  100000

In [170]:
#1
merged_data = pd.merge(
    sales,
    reprensentatives,
    left_on="region",
    right_on="region",
    how = "outer"
)
merged_data

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount,sales_rep,target
0,103,Keyboard,EAST,3,1500,2026-01-07,0.06,Pending,4500,270,Rahul,60000.0
1,107,Keyboard,EAST,4,1500,2026-01-11,0.06,Completed,6000,360,Rahul,60000.0
2,112,Keyboard,EAST,2,1500,2026-01-15,0.06,Completed,3000,180,Rahul,60000.0
3,101,Laptop,NORTH,2,50000,2026-01-05,0.05,Completed,100000,5000,Arun,120000.0
4,104,Laptop,NORTH,1,50000,2026-01-08,0.05,Completed,50000,2500,Arun,120000.0
5,108,Laptop,NORTH,1,50000,2026-01-12,0.05,Completed,50000,2500,Arun,120000.0
6,102,Mouse,SOUTH,5,500,2026-01-06,0.10,Completed,2500,250,Priya,80000.0
7,106,Mouse,SOUTH,0,500,2026-01-10,0.10,Cancelled,0,0,Priya,80000.0
8,111,Mouse,UNKNOWN,3,500,2026-01-14,0.10,Completed,1500,150,NaN,NaN
9,105,Monitor,WEST,2,12000,2026-01-09,0.08,Completed,24000,1920,Meena,100000.0
10,110,Monitor,WEST,2,12000,2026-01-13,0.06,Pending,24000,1440,Meena,100000.0

In [ ]:
#2 Unmtched
unmatched = pd.merge(
    sales,
    reprensentatives,
    on="region",
    how="left",
    indicator=True
)

unmatched = unmatched[unmatched["_merge"] == "left_only"]
unmatched

,sale_id,product,region,quantity,price,sale_date,commission_pct,sale_status,revenue,commission_amount,sales_rep,target,_merge
9,111,Mouse,UNKNOWN,3,500,2026-01-14,0.1,Completed,1500,150,NaN,NaN,left_only

In [172]:
#3
rev_sales_rep = (
    merged_data
    .groupby("sales_rep")["revenue"]
    .sum()
    .reset_index()
)
rev_sales_rep

  sales_rep  revenue
0      Arun   200000
1     Meena    48000
2     Priya     2500
3     Rahul    13500

In [ ]:
#4
# Step 1: Calculate total revenue for each region
com_regional_vs_target = (
    merged_data
    .groupby(["region", "target"])["revenue"]
    .sum()
    .reset_index()
)

# Step 2: Calculate the difference between revenue and target
com_regional_vs_target["difference"] = (
    com_regional_vs_target["revenue"] - com_regional_vs_target["target"]
)

# Step 3: Display the result
com_regional_vs_target

  region    target  revenue  difference
0   EAST   60000.0    13500    -46500.0
1  NORTH  120000.0   200000     80000.0
2  SOUTH   80000.0     2500    -77500.0
3   WEST  100000.0    48000    -52000.0

In [210]:
summary_table_c = (
    sales
    .groupby("region")
    .agg(
        total_revenue = ("revenue", "sum"),
        average_sale = ("revenue","mean")
    )
    .reset_index()
)
summary_table_c

    region  total_revenue  average_sale
0     EAST          13500   4500.000000
1    NORTH         200000  66666.666667
2    SOUTH           2500   1250.000000
3  UNKNOWN           1500   1500.000000
4     WEST          48000  24000.000000

---

### **Stage 6 — Export your report 📁**

Objective: Produce a result that another person can use.

Tasks:
1. Export the cleaned sales dataset to a CSV file.
2. Export the product revenue summary.
3. Export the regional performance report.
4. Ensure the exported files don't contain an unnecessary DataFrame index.

Function to revise:

to_csv().

Your final outputs might be:
- cleaned_sales.csv
- product_revenue_summary.csv
- regional_performance.csv

In [204]:
cleaned_data.to_csv("/Users/gokulraj/Documents/VS/Python/07_Pandas/cleaned_data(practice).csv", index = False)

In [205]:

total_revenue_per_product.to_csv("/Users/gokulraj/Documents/VS/Python/07_Pandas/total_revenue_per_product(practice).csv", index = False)

In [211]:
summary_table_c.to_csv("/Users/gokulraj/Documents/VS/Python/07_Pandas/summary_table(practice).csv", index = False)