### **Requirements:**
1. Calculate the total revenue for each record using price * quantity.
2. Calculate the overall revenue across all records.
3. Count how many records have a quantity greater than zero.
4. Identify records where the quantity is zero.
5. Write a function called analyze_sales() that performs these calculations and returns the results.

In [1]:
sales = [
    {"product": "Laptop", "price": 50000, "quantity": 2},
    {"product": "Mouse", "price": 500, "quantity": 5},
    {"product": "Keyboard", "price": 1500, "quantity": 3},
    {"product": "Laptop", "price": 50000, "quantity": 1},
    {"product": "Mouse", "price": 500, "quantity": 0},
]

In [ ]:
def analyze_sales(sales):

    overall_revenue = 0
    total_records = 0
    zero_records = 0

    for items in sales:
        print(f"Total Revenu for {items['produc']} is {items['price']* items['quantity']}")

    for items in sales:
        overall_revenue += items["price"] *  items["quantity"]

    print("Overall revenue: ", overall_revenue)

    for items in sales:
        if items["quantity"]>0:
            total_records += 1 
    print("Records with quantity greater than zero: ",total_records)

    for items in sales:
        if items["quantity"]==0:
            zero_records += 1
    print("Records with zero quantity: ", zero_records) 

    return overall_revenue, total_records, zero_records

analyze_sales(sales)

Total Revenu for Laptop is 100000
Total Revenu for Mouse is 2500
Total Revenu for Keyboard is 4500
Total Revenu for Laptop is 50000
Total Revenu for Mouse is 0
Overall revenue:  157000
Records with quantity greater than zero:  4
Records with zero quantity:  1

(157000, 4, 1)

---

### **Requirements:**
Write a function called clean_employees(employees) that:
1. Identifies employees whose age is missing (None).
2. Identifies employees whose salary is missing (None).
3. Counts how many employees have both age and salary available.
4. Returns these three results.

In [1]:
employees = [
    {"id": 1, "name": "Rahul", "age": 25, "salary": 30000},
    {"id": 2, "name": "Priya", "age": None, "salary": 35000},
    {"id": 3, "name": "Arun", "age": 28, "salary": None},
    {"id": 4, "name": "Sneha", "age": 24, "salary": 32000},
    {"id": 5, "name": "Kiran", "age": None, "salary": None},
]

In [16]:
def clean_employees(employees):
    
    missing_age=0
    missing_salary=0
    both=0

    for emp in employees:
        if emp['age'] is None:
            missing_age += 1

        if emp['salary'] is None:
            missing_salary += 1
            
        if  (emp['age'] is  not None ) and (emp['salary'] is not None):
            both += 1
            

    print("Employees with missing age", missing_age)
    print("Employees with missing salary", missing_salary)
    print("Employees with both values available", both)

    return missing_age, missing_salary, both


clean_employees(employees)

Employees with missing age 2
Employees with missing salary 2
Employees with both values available 2

(2, 2, 2)

---

### **Task**
Using Python's built-in csv module:
1. Open and read sales.csv.
2. Calculate the revenue for each record using price × quantity.
3. Calculate the overall revenue.
4. Count how many records have a quantity greater than zero.

In [35]:
import csv

with open("/Users/gokulraj/Documents/VS/Python/11_Mini_learning_project/Data/sales.csv","r") as file:
    reader = csv.DictReader(file)
    #----------------------------------
    total_revenue=0
    overall_revenue=0
    not_zoro=0

    for emp in reader:
        price = int(emp["price"])
        quantity = int(emp["quantity"])

        total_revenue = price * quantity
        overall_revenue += total_revenue

        if quantity>0:
            not_zoro += 1

        print(f"The Total Revanue for {emp['product']} is {total_revenue}")

    print("Overall revenue: ", overall_revenue)
    print("Number of records have quantity greater than zero are: ", not_zoro)

The Total Revanue for Laptop is 100000
The Total Revanue for Mouse is 2500
The Total Revanue for Keyboard is 4500
The Total Revanue for Laptop is 50000
The Total Revanue for Mouse is 0
Overall revenue:  157000
Number of records have quantity greater than zero are:  4

---

#### Assessment - Pandas
### **Your tasks**
1. Load the CSV using pd.read_csv().
2. Create a revenue column using price × quantity.
3. Calculate the overall revenue.
4. Count records where quantity > 0.
5. Display the product and revenue columns.

In [1]:
import pandas as pd

sales = pd.read_csv("/Users/gokulraj/Documents/VS/Python/11_Mini_learning_project/Data/sales.csv")

sales.head()

    product  price  quantity
0    Laptop  50000         2
1     Mouse    500         5
2  Keyboard   1500         3
3    Laptop  50000         1
4     Mouse    500         0

In [19]:
sales["revenue"] = sales["price"]*sales["quantity"]
sales.head()

    product  price  quantity  revenue
0    Laptop  50000         2   100000
1     Mouse    500         5     2500
2  Keyboard   1500         3     4500
3    Laptop  50000         1    50000
4     Mouse    500         0        0

In [20]:
print(sales["revenue"].sum())

157000

In [21]:
positive_quantity  = sales["quantity"] > 0

print(positive_quantity.sum())

4

In [22]:
sales[["product","revenue"]]

    product  revenue
0    Laptop   100000
1     Mouse     2500
2  Keyboard     4500
3    Laptop    50000
4     Mouse        0