# Handling_misssing_data

In [ ]:
import pandas as pd

# loading the data
toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [2]:
toyota_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [4]:
toyota_data.isnull().sum()

sale_id              0
sale_rep_id          0
sale_date            0
car_model            0
sale_amount          0
commission_pct    1274
sale_status          0
dtype: int64

In [12]:
#remove the null to 0
toyota_data['commission_pct'] = toyota_data['commission_pct'].fillna(0)

In [13]:
toyota_data.isnull().sum()

sale_id           0
sale_rep_id       0
sale_date         0
car_model         0
sale_amount       0
commission_pct    0
sale_status       0
dtype: int64

---

**Remove the rows or Data Where commission_pct is null using "Dropna(subset[])"**

In [16]:
import pandas as pd

# loading the data
toyota_data1 = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [17]:
toyota_data1.isnull().sum()

sale_id              0
sale_rep_id          0
sale_date            0
car_model            0
sale_amount          0
commission_pct    1274
sale_status          0
dtype: int64

In [18]:
toyota_data1 = toyota_data1.dropna(subset=['commission_pct'])

In [19]:
toyota_data1.isnull().sum()

sale_id           0
sale_rep_id       0
sale_date         0
car_model         0
sale_amount       0
commission_pct    0
sale_status       0
dtype: int64

In [20]:
toyota_data1.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed
8,9,9,2024-11-25,RAV4,29690.54,0.03,Pending

---

**To check the "median" Value**

**And fill the Null value to median value**

In [21]:
import pandas as pd

# loading the data
toyota_data2 = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [22]:
median_commision = toyota_data2["commission_pct"].median()

In [23]:
median_commision

np.float64(0.03)

In [24]:
toyota_data2["commission_pct"] = toyota_data2["commission_pct"].fillna(median_commision)

In [26]:
toyota_data2.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.03,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.03,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.03,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

-------

# Remove_Duplicates

In [1]:
import pandas as pd

# Create a custom DataFrame with intentional duplicates
data = [
    {"sale_id": 1, "sale_rep_id": 101, "sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": 30000, "commission_pct": 6, "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 4, "sale_rep_id": 104, "sale_date": "2024-01-04", "car_model": "Highlander", "sale_amount": 35000, "commission_pct": 7, "sale_status": "Pending"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": 30000, "commission_pct": 6, "sale_status": "Completed"},
]

In [3]:
#converting it into Dataframe

df = pd.DataFrame(data)

In [5]:
#Display the DataFrame
df

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed
2,3,103,2024-01-03,RAV4,30000,6,Completed
3,2,102,2024-01-02,Corolla,18000,4,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending
5,3,103,2024-01-03,RAV4,30000,6,Completed

**duplicated()**

To find the Duplicates

In [13]:
#The First occurance is not considired as duplicates, The Second occurance is considired as duplicates

df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [11]:
#To display duplicates rows
df[df.duplicated()]

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
3,2,102,2024-01-02,Corolla,18000,4,Completed
5,3,103,2024-01-03,RAV4,30000,6,Completed

**drop_duplicates()**

To Remove the duplicates

In [14]:
#To Remove duplicates
df_cleaned = df.drop_duplicates()

In [15]:
df_cleaned

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
1,2,102,2024-01-02,Corolla,18000,4,Completed
2,3,103,2024-01-03,RAV4,30000,6,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending

---

In some ceses ther might be Data where the single column has duplicates, but the other colunm has different value data

In [2]:
import pandas as pd

# Create a custom DataFrame with intentional duplicates
data = [
    {"sale_id": 1, "sale_rep_id": 101, "sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": 30000, "commission_pct": 6, "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "corolla", "sale_amount": 19000, "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 4, "sale_rep_id": 104, "sale_date": "2024-01-04", "car_model": "Highlander", "sale_amount": 35000, "commission_pct": 7, "sale_status": "Pending"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": 30000, "commission_pct": 6, "sale_status": "Completed"},
]

In [3]:
df = pd.DataFrame(data)

* 'first' : Drop duplicates except for the first occurrence.
* 'last' : Drop duplicates except for the last occurrence.
* `False` : Drop all duplicates.(Default)

In [4]:
### Remove duplicates based on a specific column


df.drop_duplicates(
    subset=["sale_id"],
    keep="last"
)


### Quick memory
#Same ID → multiple updates → keep latest row.**

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,101,2024-01-01,Camry,20000,5,Completed
3,2,102,2024-01-02,corolla,19000,4,Completed
4,4,104,2024-01-04,Highlander,35000,7,Pending
5,3,103,2024-01-03,RAV4,30000,6,Completed

---

# Rename_And_Reorder_Column

In [2]:
import pandas as pd

toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data_no_header.csv")

In [ ]:
#No Header,So make the First row as Header as default
toyota_data.head(3)

   1  16  2024-11-18   Tundra  44496.88  0.05  Completed
0  2  11  2024-11-08   Tacoma  34824.72   NaN    Pending
1  3   5  2024-11-03  Corolla  20275.08   NaN  Completed
2  4  20  2024-11-06  Corolla  20068.93   NaN  Completed

In [ ]:
toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data_no_header.csv",
      header=None
)

#header=None:- Removes the first row as header and gives index number

In [ ]:
toyota_data.head(3)

   0   1           2        3         4     5          6
0  1  16  2024-11-18   Tundra  44496.88  0.05  Completed
1  2  11  2024-11-08   Tacoma  34824.72   NaN    Pending
2  3   5  2024-11-03  Corolla  20275.08   NaN  Completed

**To Add the header**

In [12]:
toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data_no_header.csv",
      header=None,
      names=["sale_id", "sale_rep_id", "sale_date", "car_model",
              "sale_amount", "commission_pct", "sale_status"]

)

In [13]:
toyota_data.head(4)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed

**TO Change or modify the Column Name**

In [16]:
toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [17]:
toyota_data.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

In [18]:
toyota_data_rename = toyota_data.rename(columns={"commission_pct" : "commission_percentage"})

In [19]:
toyota_data_rename.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_percentage', 'sale_status'],
      dtype='str')

**Reorder The Column**

In [20]:
toyota_data.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

In [21]:
column_reordered = ['sale_id','sale_date' ,'sale_rep_id' , 'car_model', 'sale_amount',
       'commission_pct', 'sale_status']

In [22]:
toyota_data_reordered = toyota_data[column_reordered]

In [23]:
toyota_data_reordered.columns

Index(['sale_id', 'sale_date', 'sale_rep_id', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

In [25]:
toyota_data_reordered.head()

,sale_id,sale_date,sale_rep_id,car_model,sale_amount,commission_pct,sale_status
0,1,2024-11-18,16,Tundra,44496.88,0.05,Completed
1,2,2024-11-08,11,Tacoma,34824.72,NaN,Pending
2,3,2024-11-03,5,Corolla,20275.08,NaN,Completed
3,4,2024-11-06,20,Corolla,20068.93,NaN,Completed
4,5,2024-11-26,1,Tundra,49811.99,0.03,Completed

Convert all the Header into Upper Case

In [26]:
toyota_data_upper = toyota_data.rename(columns= str.upper)

In [27]:
toyota_data_upper.head(4)

,SALE_ID,SALE_REP_ID,SALE_DATE,CAR_MODEL,SALE_AMOUNT,COMMISSION_PCT,SALE_STATUS
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed

---

# Handling_Datatypes

In [31]:
import pandas as pd

# Create a custom DataFrame with intentional duplicates
data = [
    {"sale_id": 1, "sale_rep_id": 101, "sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": "20000", "commission_pct": 5, "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": "18000", "commission_pct": 4, "sale_status": "Completed"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": "30000", "commission_pct": 6, "sale_status": "Completed"},
    {"sale_id": 4, "sale_rep_id": 104, "sale_date": "2024-01-04", "car_model": "Highlander", "sale_amount": "35000", "commission_pct": 7, "sale_status": "Pending"},
]

df = pd.DataFrame(data)

In [32]:
df.dtypes

sale_id           int64
sale_rep_id       int64
sale_date           str
car_model           str
sale_amount         str
commission_pct    int64
sale_status         str
dtype: object

In [ ]:
#Converting to DateTime
df["sale_date"]= pd.to_datetime(df["sale_date"])

In [39]:
#Converting to Numeric
df["sale_amount"] = pd.to_numeric(df["sale_amount"])

In [44]:
df.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[us]
car_model                    str
sale_amount                int64
commission_pct             int64
sale_status                  str
dtype: object

In [ ]:

toyota_data = pd.read_csv("/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv")

In [45]:
toyota_data.dtypes

sale_id             int64
sale_rep_id         int64
sale_date             str
car_model             str
sale_amount       float64
commission_pct    float64
sale_status           str
dtype: object

In [47]:
toyota_data["sale_date"] = pd.to_datetime(toyota_data["sale_date"])

In [50]:
toyota_data["car_model"] = toyota_data["car_model"].astype("category")

In [51]:
toyota_data["sale_status"] = toyota_data["sale_status"].astype("category")

In [52]:
toyota_data.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[us]
car_model               category
sale_amount              float64
commission_pct           float64
sale_status             category
dtype: object

***category is a Pandas data type used for columns that contain a limited number of repeated text values.***

It can "reduce memory" usage when a column has many repeated values.

For example:

sale_status
______________________
* Completed
* Pending
* Completed
* Cancelled
* Pending
* Completed

In [ ]:
#Unique Values
toyota_data.nunique()

sale_id           5000
sale_rep_id         20
sale_date           30
car_model            6
sale_amount       4996
commission_pct       3
sale_status          3
dtype: int64

**Use_Case :- display Sales Complete data**

In [ ]:
toyota_data_complete = toyota_data[
    toyota_data["sale_status"] == "Completed"
]

In [65]:
toyota_data_complete.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed

In [64]:
#Sort By Date
toyota_data[toyota_data["sale_status"] == "Completed"].sort_values(by= "sale_date")

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
4445,4446,18,2024-11-01,Camry,26460.96,NaN,Completed
316,317,1,2024-11-01,Camry,27690.66,0.03,Completed
2728,2729,1,2024-11-01,Corolla,22248.02,0.05,Completed
153,154,20,2024-11-01,RAV4,27486.46,NaN,Completed
4097,4098,17,2024-11-01,Tundra,48422.66,NaN,Completed
...,...,...,...,...,...,...,...
2658,2659,17,2024-11-30,Camry,27133.62,0.03,Completed
3903,3904,19,2024-11-30,Camry,28494.06,0.02,Completed
745,746,9,2024-11-30,Highlander,41530.72,0.02,Completed
1024,1025,18,2024-11-30,Camry,26696.07,0.03,Completed
2631,2632,13,2024-11-30,RAV4,28041.83,0.05,Completed

---

# Filtering
And_Subsetting_Data

In [ ]:
import pandas as pd

toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv"
    )

In [5]:
toyota_data.dtypes

sale_id             int64
sale_rep_id         int64
sale_date             str
car_model             str
sale_amount       float64
commission_pct    float64
sale_status           str
dtype: object

In [6]:
toyota_data["sale_date"] = pd.to_datetime(toyota_data["sale_date"])

In [7]:
toyota_data.dtypes

sale_id                    int64
sale_rep_id                int64
sale_date         datetime64[us]
car_model                    str
sale_amount              float64
commission_pct           float64
sale_status                  str
dtype: object

**Filtering with Conditional**

Example: Filter where sales amount is greater than 30000

In [11]:
highest_sales = toyota_data[toyota_data["sale_amount"] > 30000]

In [ ]:
#subsetting
highest_sales.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed

Example: Filter where sales amount is greater than 30000 and sales_status is completed

In [ ]:
highest_sales_completed = toyota_data[
    (toyota_data["sale_amount"] > 30000) & (toyota_data["sale_status"] == "Completed")
]

#Note: we can't use "&" b/w string and interger value (throws error), we seperate with ()

In [20]:
highest_sales_completed

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed
6,7,12,2024-11-30,RAV4,33073.24,0.03,Completed
10,11,12,2024-11-11,Highlander,40044.87,0.02,Completed
...,...,...,...,...,...,...,...
4988,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed
4989,4990,10,2024-11-15,Tundra,38116.14,0.02,Completed
4990,4991,20,2024-11-17,Highlander,36500.60,NaN,Completed
4992,4993,10,2024-11-26,Tundra,47497.87,0.02,Completed
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed

Example: Filter where sales amount is greater than 30000 and diplay sale_id,  car_model,sale_amount

In [25]:
#this is the resone we use "loc", which gives us more control over the data
high_sales_subset = toyota_data.loc[
    toyota_data["sale_amount"] > 30000, 
    ["sale_id", "car_model", "sale_amount"]
]

In [26]:
high_sales_subset

      sale_id   car_model  sale_amount
0           1      Tundra     44496.88
1           2      Tacoma     34824.72
4           5      Tundra     49811.99
5           6        RAV4     34346.20
6           7        RAV4     33073.24
...       ...         ...          ...
4990     4991  Highlander     36500.60
4992     4993      Tundra     47497.87
4994     4995      Tundra     41202.36
4997     4998      Tacoma     30780.39
4999     5000      Tundra     44525.85

[2976 rows x 3 columns]

# sql like filtering 

using (.qurey)

In [1]:
import pandas as pd

toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv"
    )

In [2]:
toyota_data.head(4)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed

In [3]:
#we can also Boolen operator and have multiple contion using .query
toyota_data.query("car_model == 'Camry' and sale_status == 'Completed'" )

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
7,8,3,2024-11-05,Camry,25561.86,NaN,Completed
9,10,14,2024-11-09,Camry,27321.71,0.03,Completed
44,45,14,2024-11-01,Camry,26362.15,NaN,Completed
63,64,18,2024-11-20,Camry,26159.94,NaN,Completed
69,70,11,2024-11-12,Camry,26260.96,0.02,Completed
...,...,...,...,...,...,...,...
4956,4957,6,2024-11-24,Camry,26444.97,NaN,Completed
4957,4958,20,2024-11-08,Camry,26830.46,0.03,Completed
4973,4974,6,2024-11-07,Camry,25577.80,NaN,Completed
4991,4992,6,2024-11-03,Camry,27247.36,0.03,Completed
4993,4994,4,2024-11-07,Camry,26498.13,0.05,Completed

**All-In-One**

Example:- Display, where sale_amount is greater than 30k with status completed of car_model is Rav4 (include only: car_model, sale_amount, sale_status)

In [10]:
#normal method using .loc
high_sales_subset = toyota_data.loc[
    (toyota_data["sale_amount"] > 30000) & 
    (toyota_data['sale_status'] == "Completed") &
    (toyota_data["car_model"] == 'RAV4'),
    ["car_model", "sale_amount", "sale_status"]
]

In [11]:
high_sales_subset

     car_model  sale_amount sale_status
5         RAV4     34346.20   Completed
6         RAV4     33073.24   Completed
17        RAV4     32751.81   Completed
28        RAV4     30624.47   Completed
29        RAV4     31643.54   Completed
...        ...          ...         ...
4953      RAV4     30894.22   Completed
4971      RAV4     31604.19   Completed
4979      RAV4     30446.63   Completed
4980      RAV4     30452.77   Completed
4988      RAV4     31543.36   Completed

[395 rows x 3 columns]

In [ ]:
# using qurey method
toyota_data.query(
    "car_model == 'RAV4' and sale_status == 'Completed' and sale_amount > 30000"
 )[[ "car_model", "sale_amount", "sale_status"]] 
# warning: if we try to write the code which is in the [[]] in next line, output(empty)

     car_model  sale_amount sale_status
5         RAV4     34346.20   Completed
6         RAV4     33073.24   Completed
17        RAV4     32751.81   Completed
28        RAV4     30624.47   Completed
29        RAV4     31643.54   Completed
...        ...          ...         ...
4953      RAV4     30894.22   Completed
4971      RAV4     31604.19   Completed
4979      RAV4     30446.63   Completed
4980      RAV4     30452.77   Completed
4988      RAV4     31543.36   Completed

[395 rows x 3 columns]

---

# Sorting_Data

In [14]:
import pandas as pd

toyota_data = pd.read_csv(
    "/Users/gokulraj/Documents/VS/Project/autosales_insights/Data/car_sales/toyota_sales_data.csv"
    )

In [18]:
#Correcting Datatypes
toyota_data["sale_date"] = pd.to_datetime(toyota_data["sale_date"])

In [ ]:
#Sort the sale_amount in Asending order
sorted_by_amount_asc = toyota_data.sort_values(by="sale_amount")

In [24]:
sorted_by_amount_asc

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
2275,2276,12,2024-11-08,Corolla,20000.94,0.05,Pending
2464,2465,16,2024-11-02,Corolla,20001.20,0.05,Completed
2488,2489,16,2024-11-27,Corolla,20001.37,0.02,Pending
2871,2872,2,2024-11-16,Corolla,20003.27,0.05,Completed
4910,4911,6,2024-11-23,Corolla,20004.62,0.03,Completed
...,...,...,...,...,...,...,...
2577,2578,7,2024-11-18,Tundra,49923.84,0.02,Completed
3934,3935,6,2024-11-27,Tundra,49942.26,0.05,Completed
1901,1902,3,2024-11-12,Tundra,49974.88,0.02,Cancelled
685,686,8,2024-11-17,Tundra,49979.12,0.02,Completed
2877,2878,15,2024-11-02,Tundra,49995.68,NaN,Pending

In [ ]:
#Sort the sale_amount in Desending order
sorted_by_amount_dec = toyota_data.sort_values(by="sale_amount", ascending=False)

In [ ]:
sorted_by_amount_dec

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
2877,2878,15,2024-11-02,Tundra,49995.68,NaN,Pending
685,686,8,2024-11-17,Tundra,49979.12,0.02,Completed
1901,1902,3,2024-11-12,Tundra,49974.88,0.02,Cancelled
3934,3935,6,2024-11-27,Tundra,49942.26,0.05,Completed
2577,2578,7,2024-11-18,Tundra,49923.84,0.02,Completed
...,...,...,...,...,...,...,...
4910,4911,6,2024-11-23,Corolla,20004.62,0.03,Completed
2871,2872,2,2024-11-16,Corolla,20003.27,0.05,Completed
2488,2489,16,2024-11-27,Corolla,20001.37,0.02,Pending
2464,2465,16,2024-11-02,Corolla,20001.20,0.05,Completed
2275,2276,12,2024-11-08,Corolla,20000.94,0.05,Pending

In [ ]:
#Sort the sale_date, sale_status in ascending
sorted_by_date_status = toyota_data.sort_values(by=["sale_date", "sale_status"])
# (by=) parameter alows a list of columns

In [35]:
sorted_by_date_status

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
26,27,7,2024-11-01,Tacoma,30218.18,0.03,Cancelled
263,264,2,2024-11-01,RAV4,30908.43,0.03,Cancelled
995,996,13,2024-11-01,Corolla,21044.21,0.03,Cancelled
2169,2170,9,2024-11-01,Tundra,39923.78,0.03,Cancelled
2214,2215,9,2024-11-01,Tundra,35228.92,NaN,Cancelled
...,...,...,...,...,...,...,...
4625,4626,7,2024-11-30,RAV4,28431.57,0.05,Pending
4636,4637,19,2024-11-30,Highlander,35042.28,0.05,Pending
4708,4709,18,2024-11-30,RAV4,32612.70,0.05,Pending
4735,4736,11,2024-11-30,RAV4,31519.06,0.05,Pending
4748,4749,10,2024-11-30,Tacoma,36242.95,NaN,Pending

Use Case:- Most recent "Completed" sales by sale_date in decending order

In [41]:
toyota_data[toyota_data["sale_status"] == "Completed"]  \
    .sort_values(by="sale_date", ascending=False)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
3204,3205,4,2024-11-30,Tundra,39733.80,0.03,Completed
3076,3077,14,2024-11-30,RAV4,33632.71,0.03,Completed
3248,3249,1,2024-11-30,RAV4,29887.44,0.02,Completed
3233,3234,17,2024-11-30,RAV4,27260.43,0.03,Completed
3219,3220,16,2024-11-30,Camry,25225.16,0.05,Completed
...,...,...,...,...,...,...,...
1139,1140,11,2024-11-01,RAV4,34596.69,NaN,Completed
1140,1141,8,2024-11-01,Tacoma,39741.88,0.03,Completed
2164,2165,2,2024-11-01,Corolla,24814.51,NaN,Completed
2162,2163,12,2024-11-01,Tacoma,38937.54,0.03,Completed
348,349,17,2024-11-01,Tundra,41372.43,0.02,Completed

---

# Practical Session

In [1]:
import pandas as pd

# Create a custom DataFrame with intentional duplicates
data = [
    {"sale_id": 1, "sale_rep_id": 101, "sale_date": "2024-01-01", "car_model": "Camry", "sale_amount": 20000, "priority": "High", "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000, "priority": "Medium", "sale_status": "Completed"},
    {"sale_id": 3, "sale_rep_id": 103, "sale_date": "2024-01-03", "car_model": "RAV4", "sale_amount": 30000, "priority": "High" , "sale_status": "Completed"},
    {"sale_id": 2, "sale_rep_id": 102, "sale_date": "2024-01-02", "car_model": "Corolla", "sale_amount": 18000,"priority": "Medium", "sale_status": "Completed"},
    {"sale_id": 4, "sale_rep_id": 104, "sale_date": "2024-01-04", "car_model": "Highlander", "sale_amount": 35000, "priority": "Low", "sale_status": "Pending"}
]

custom_df = pd.DataFrame(data)

In [2]:
custom_df

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
1,2,102,2024-01-02,Corolla,18000,Medium,Completed
2,3,103,2024-01-03,RAV4,30000,High,Completed
3,2,102,2024-01-02,Corolla,18000,Medium,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending

In [3]:
#Remove duplicates
deduplicated_df = custom_df.drop_duplicates(subset='sale_id')

In [4]:
deduplicated_df

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
1,2,102,2024-01-02,Corolla,18000,Medium,Completed
2,3,103,2024-01-03,RAV4,30000,High,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending

In [5]:
custom_df.sort_values(by="priority") 
#Note: Wrong, since the order of soring should be(high-medium-low)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
2,3,103,2024-01-03,RAV4,30000,High,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending
1,2,102,2024-01-02,Corolla,18000,Medium,Completed
3,2,102,2024-01-02,Corolla,18000,Medium,Completed

**custom priority_order type**

In [ ]:
#Covert the "priority" datatype to category
#it's  not default category type, it's custom priority_order type
priority_order = pd.CategoricalDtype(categories=['High','Medium','Low'])

In [7]:
custom_df['priority'] = custom_df['priority'].astype(priority_order)

In [8]:
custom_df.dtypes

sale_id           int64
sale_rep_id       int64
sale_date           str
car_model           str
sale_amount       int64
priority       category
sale_status         str
dtype: object

In [9]:
custom_df.sort_values(by="priority")

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,priority,sale_status
0,1,101,2024-01-01,Camry,20000,High,Completed
2,3,103,2024-01-03,RAV4,30000,High,Completed
1,2,102,2024-01-02,Corolla,18000,Medium,Completed
3,2,102,2024-01-02,Corolla,18000,Medium,Completed
4,4,104,2024-01-04,Highlander,35000,Low,Pending

---

# Merging_and_Joining Datasets

Different Types of joins
* Inner Join :- Gives Matching keys in both Tables 
* Left Join :- All Data from left and only matching from Right 
* Right Join :- All Data from Right and only matching from Left
* Outer Join :- Gives all the Data from both the table and marks unmatched rows as NaN

# Best Practices for Joins

* Specify the Parent Table First
* validate Keys
* Inspect Missing Data

***Use Case:-* Find all sales_rep who has made the sales and include only matching records**

In [2]:
import pandas as pd

In [3]:
# Sales Representative Table (Parent)
sales_reps = pd.DataFrame({
    "rep_id": [1, 2, 3],
    "name": ["Goku", "Luffy", "Guts"],
    "region": ["North", "South", "West"]
})

In [4]:
# Sales Data Table (Child)

sales = pd.DataFrame({
    "sale_id": [101, 102, 103, 104 ],
    "sale_rep_id": [1, 2, None, 4], 
    "sale_amount": [500, 1000, 750, 1200]
})

In [18]:
sales_reps

   rep_id   name region
0       1   Goku  North
1       2  Luffy  South
2       3   Guts   West

In [19]:
sales

   sale_id  sale_rep_id  sale_amount
0      101          1.0          500
1      102          2.0         1000
2      103          NaN          750
3      104          4.0         1200

**`Inner Joins`**

In [20]:
inner_join = pd.merge(
    sales_reps, #table_1
    sales,  #table_2
    left_on="rep_id", #primary_key of first table
    right_on="sale_rep_id", #forign_key of second table
    how="inner" #Joining method
)

In [21]:
inner_join

   rep_id   name region  sale_id  sale_rep_id  sale_amount
0       1   Goku  North      101          1.0          500
1       2  Luffy  South      102          2.0         1000

**`Left Joins`**

**Use Case:-** Display the sales_reprenataive who has not made any sales

In [ ]:
left_join = pd.merge(
    sales_reps,
    sales,
    left_on= "rep_id",
    right_on = "sale_rep_id",
    how= "left"
)

In [30]:
left_join

   rep_id   name region  sale_id  sale_rep_id  sale_amount
0       1   Goku  North    101.0          1.0        500.0
1       2  Luffy  South    102.0          2.0       1000.0
2       3   Guts   West      NaN          NaN          NaN

In [ ]:
#filtering the null rows using pandas .isnull()
inactive_reps = left_join[left_join["sale_id"].isnull()]

In [34]:
inactive_reps

   rep_id  name region  sale_id  sale_rep_id  sale_amount
2       3  Guts   West      NaN          NaN          NaN

In [35]:
#filtering the null rows using pandas sql-like query
left_join.query("sale_id.isnull()")

   rep_id  name region  sale_id  sale_rep_id  sale_amount
2       3  Guts   West      NaN          NaN          NaN

`Right Join`

**Use Case:-**  Find orphan sales records(child table has additional records with no value in parent table )

In [5]:
right_join = pd.merge(
    sales_reps,
    sales,
    left_on="rep_id",
    right_on="sale_rep_id",
    how="right"
)

In [6]:
right_join

   rep_id   name region  sale_id  sale_rep_id  sale_amount
0     1.0   Goku  North      101          1.0          500
1     2.0  Luffy  South      102          2.0         1000
2     NaN    NaN    NaN      103          NaN          750
3     NaN    NaN    NaN      104          4.0         1200

In [7]:
orphan_data = right_join[right_join["rep_id"].isnull()]

In [8]:
orphan_data

   rep_id name region  sale_id  sale_rep_id  sale_amount
2     NaN  NaN    NaN      103          NaN          750
3     NaN  NaN    NaN      104          4.0         1200

In [9]:
right_join.fillna({"name":"unknown", "region":"unknown", "sale_rep_id":"unknown"}, inplace=True)

#inplace=True → modify the original DataFrame directly
#inplace=False (default) → return a modified copy; original stays unchanged

   rep_id     name   region  sale_id sale_rep_id  sale_amount
0     1.0     Goku    North      101         1.0          500
1     2.0    Luffy    South      102         2.0         1000
2     NaN  unknown  unknown      103     unknown          750
3     NaN  unknown  unknown      104         4.0         1200

`LEFT JOIN` → Keep all main data; add matching information from the other table

* Example: Keep all sales, add customer details. Missing customer → NaN

`RIGHT JOIN` → Keep all data from the other/master table; add matching information

* Example: Keep all employees, even those with no sales.

**`Outer Join`**

A full outer join in pandas keeps all records from both DataFrames, matching the common records and filling unmatched values with NaN.

In [ ]:
import pandas as pd

In [10]:
# Sales Representatives Table (Parent)
sales_reps = pd.DataFrame({
    "rep_id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"],
    "region": ["North", "South", "West"]
})


# Sales Data Table (Child)
sales = pd.DataFrame({
    "sale_id": [101, 102, 103, 104],
    "sale_rep_id": [1, 2, None, 4],  # Includes a missing and an unmatched ID
    "sale_amount": [500, 1000, 750, 1200]
})

In [12]:
outer_join = pd.merge(
    sales_reps,
    sales,
    left_on = "rep_id",
    right_on = "sale_rep_id",
    how = "outer"
)

In [13]:
outer_join

   rep_id     name region  sale_id  sale_rep_id  sale_amount
0     1.0    Alice  North    101.0          1.0        500.0
1     2.0      Bob  South    102.0          2.0       1000.0
2     3.0  Charlie   West      NaN          NaN          NaN
3     NaN      NaN    NaN    104.0          4.0       1200.0
4     NaN      NaN    NaN    103.0          NaN        750.0

In [14]:
inactive_reps = outer_join[outer_join["sale_id"].isnull()]

In [15]:
inactive_reps

   rep_id     name region  sale_id  sale_rep_id  sale_amount
2     3.0  Charlie   West      NaN          NaN          NaN

In [17]:
outer_join.query("sale_id.isnull()")

   rep_id     name region  sale_id  sale_rep_id  sale_amount
2     3.0  Charlie   West      NaN          NaN          NaN

In [18]:
orphand_sales = outer_join[outer_join["rep_id"].isnull()]

In [19]:
orphand_sales

   rep_id name region  sale_id  sale_rep_id  sale_amount
3     NaN  NaN    NaN    104.0          4.0       1200.0
4     NaN  NaN    NaN    103.0          NaN        750.0

In [27]:
outer_join.fillna({"rep_id":"unknown", "name":"unknown", "region":"unknown", "sale_id": "0",  "sale_rep_id":"0", "sale_amount": "0"}, inplace= True)

    rep_id     name   region sale_id sale_rep_id sale_amount
0      1.0    Alice    North   101.0         1.0       500.0
1      2.0      Bob    South   102.0         2.0      1000.0
2      3.0  Charlie     West       0           0           0
3  unknown  unknown  unknown   104.0         4.0      1200.0
4  unknown  unknown  unknown   103.0           0       750.0

---

**Real world Example**

In [33]:
import pandas as pd

sales_reps_data = pd.read_csv("Data/car_sales/sales_reps_data.csv")
toyota_sales_data = pd.read_csv("Data/car_sales/toyota_sales_data.csv")

In [36]:
sales_reps_data.columns

Index(['rep_id', 'first_name', 'last_name', 'email', 'phone_number',
       'hire_date', 'region', 'status'],
      dtype='str')

In [37]:
toyota_sales_data.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

In [38]:
merged_data = pd.merge(
    sales_reps_data,
    toyota_sales_data,
    left_on="rep_id",
    right_on = "sale_rep_id",
    how = "inner"
)

In [39]:
merged_data

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
1,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,12,1,2024-11-23,Tundra,39427.38,0.05,Cancelled
2,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,17,1,2024-11-18,Camry,26676.29,NaN,Pending
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,NaN,Completed
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,NaN,Completed
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,NaN,Completed

**Total sales as per person**

In [49]:
total_sales = merged_data.groupby(["rep_id","first_name","region"])["sale_amount"].sum().reset_index()
#.reset_index(),  add the index

In [50]:
total_sales

    rep_id   first_name region  sale_amount
0        1      Anthony  North   8793624.75
1        2       Edward  North   8721864.31
2        3         Paul   East   7483168.82
3        4       Robert  South   7473215.23
4        5       Steven   West   7814744.92
5        6        Brian   East   8089256.01
6        7  Christopher  North   8658437.14
7        8        David  North   8672081.85
8        9       Thomas   West   8623533.39
9       10  Christopher  North   7822524.30
10      11        David  North   7946648.50
11      12       Daniel   West   8493429.13
12      13       Robert  North   8012200.98
13      14       Daniel  South   8268540.28
14      15      William  North   8218385.64
15      16      Michael   East   8161330.01
16      17      Charles   West   8247398.75
17      18       Daniel  North   8759602.34
18      19       Thomas   East   8788981.01
19      20       Edward  North   7849573.71

**Calculate total commision amount**

In [51]:
merged_data["total_commision"] = merged_data["sale_amount"]* merged_data["commission_pct"]

In [ ]:
merged_data["total_commision"] =round (merged_data["sale_amount"]* merged_data["commission_pct"])
#round():- remove the decimal point and make it round(whole)

In [54]:
merged_data

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,total_commision
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.0
1,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,12,1,2024-11-23,Tundra,39427.38,0.05,Cancelled,1971.0
2,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,17,1,2024-11-18,Camry,26676.29,NaN,Pending,NaN
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,NaN,Completed,NaN
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed,1031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,NaN,Completed,NaN
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed,805.0
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed,1765.0
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed,631.0
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,NaN,Completed,NaN

**Fill the Null value**

In [56]:
merged_data.isnull().sum()

rep_id                0
first_name            0
last_name             0
email                 0
phone_number          0
hire_date             0
region                0
status                0
sale_id               0
sale_rep_id           0
sale_date             0
car_model             0
sale_amount           0
commission_pct     1274
sale_status           0
total_commision    1274
dtype: int64

In [59]:
merged_data.fillna({"commission_pct":"0", "total_commision":"0" }, inplace= True)

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,total_commision
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.0
1,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,12,1,2024-11-23,Tundra,39427.38,0.05,Cancelled,1971.0
2,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,17,1,2024-11-18,Camry,26676.29,0,Pending,0
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,0,Completed,0
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed,1031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,0,Completed,0
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed,805.0
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed,1765.0
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed,631.0
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,0,Completed,0

or

In [ ]:
merged_data["commission_pct"].fillna(0)

0       0.03
1       0.05
2          0
3          0
4       0.05
        ...
4995       0
4996    0.03
4997    0.05
4998    0.02
4999       0
Name: commission_pct, Length: 5000, dtype: object

In [65]:
merged_data[["rep_id","email","sale_amount","total_commision"]]

      rep_id                     email  sale_amount total_commision
0          1  anthony.davis@toyota.com     49811.99          1494.0
1          1  anthony.davis@toyota.com     39427.38          1971.0
2          1  anthony.davis@toyota.com     26676.29               0
3          1  anthony.davis@toyota.com     24278.39               0
4          1  anthony.davis@toyota.com     20623.99          1031.0
...      ...                       ...          ...             ...
4995      20   edward.jones@toyota.com     25686.30               0
4996      20   edward.jones@toyota.com     26830.46           805.0
4997      20   edward.jones@toyota.com     35293.57          1765.0
4998      20   edward.jones@toyota.com     31543.36           631.0
4999      20   edward.jones@toyota.com     36500.60               0

[5000 rows x 4 columns]

**Commision per rep_id**

In [96]:
import pandas as pd

sales_reps_data = pd.read_csv("Data/car_sales/sales_reps_data.csv")
toyota_sales_data = pd.read_csv("Data/car_sales/toyota_sales_data.csv")

In [97]:
merged_data = pd.merge(
    sales_reps_data,
    toyota_sales_data,
    left_on="rep_id",
    right_on = "sale_rep_id",
    how = "inner"
)

In [98]:
merged_data.columns

Index(['rep_id', 'first_name', 'last_name', 'email', 'phone_number',
       'hire_date', 'region', 'status', 'sale_id', 'sale_rep_id', 'sale_date',
       'car_model', 'sale_amount', 'commission_pct', 'sale_status'],
      dtype='str')

In [100]:
#fill null
merged_data.fillna({"sale_amount":0, "commission_pct":0}, inplace= True)

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
1,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,12,1,2024-11-23,Tundra,39427.38,0.05,Cancelled
2,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,17,1,2024-11-18,Camry,26676.29,0.00,Pending
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,0.00,Completed
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,0.00,Completed
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,0.00,Completed

In [101]:
merged_data["commission_earned"] = round(merged_data["sale_amount"] * merged_data["commission_pct"])

In [105]:
total_commision_earned = merged_data.groupby(["rep_id","first_name", "email"])["commission_earned"].sum().reset_index()

In [106]:
total_commision_earned

    rep_id   first_name                         email  commission_earned
0        1      Anthony      anthony.davis@toyota.com           229835.0
1        2       Edward       edward.smith@toyota.com           218995.0
2        3         Paul         paul.jones@toyota.com           184880.0
3        4       Robert       robert.lopez@toyota.com           191386.0
4        5       Steven      steven.wilson@toyota.com           216161.0
5        6        Brian     brian.martinez@toyota.com           189754.0
6        7  Christopher  christopher.jones@toyota.com           202114.0
7        8        David        david.davis@toyota.com           222119.0
8        9       Thomas       thomas.smith@toyota.com           211728.0
9       10  Christopher  christopher.brown@toyota.com           188086.0
10      11        David     david.gonzalez@toyota.com           190773.0
11      12       Daniel     daniel.jackson@toyota.com           219825.0
12      13       Robert   robert.hernandez@toyota.com           208535.0
13      14       Daniel    daniel.williams@toyota.com           208778.0
14      15      William      william.moore@toyota.com           207620.0
15      16      Michael   michael.martinez@toyota.com           216682.0
16      17      Charles      charles.lopez@toyota.com           200372.0
17      18       Daniel    daniel.martinez@toyota.com           220996.0
18      19       Thomas      thomas.wilson@toyota.com           224914.0
19      20       Edward       edward.jones@toyota.com           193408.0

---

# Grouping(Group by) and Aggregation

In [110]:
data= pd.read_csv("Data/car_sales/toyota_sales_data.csv")

In [111]:
data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

**Total as per status, Cancelle, Completed, Pending**

**Group by sale status, calculate total sales amount, and reset the index**

In [ ]:


total_completed_sales = data.groupby("sale_status")["sale_amount"].sum().reset_index()

In [113]:
total_completed_sales

  sale_status   sale_amount
0   Cancelled  1.262446e+07
1   Completed  1.182973e+08
2     Pending  3.397674e+07

* `groupby()` → group the data
* `["sale_amount"]` → select column
* `sum()` → calculate total
* `reset_index()` → make grouped index a normal column

**Total sale_amount per sale_rep_id**

In [ ]:


sale_rep_total = data.groupby("sale_rep_id")["sale_amount"].sum().reset_index()

In [115]:
sale_rep_total

    sale_rep_id  sale_amount
0             1   8793624.75
1             2   8721864.31
2             3   7483168.82
3             4   7473215.23
4             5   7814744.92
5             6   8089256.01
6             7   8658437.14
7             8   8672081.85
8             9   8623533.39
9            10   7822524.30
10           11   7946648.50
11           12   8493429.13
12           13   8012200.98
13           14   8268540.28
14           15   8218385.64
15           16   8161330.01
16           17   8247398.75
17           18   8759602.34
18           19   8788981.01
19           20   7849573.71

**Average sales per car model**

In [ ]:

averale_model_sale = data.groupby("car_model")["sale_amount"].median().reset_index()

In [120]:
averale_model_sale

    car_model  sale_amount
0       Camry    27448.575
1     Corolla    22477.280
2  Highlander    39988.890
3        RAV4    30922.640
4      Tacoma    34989.815
5      Tundra    42306.670

**To get total sale_amount as well as Average sale_amount, per status**

In [127]:

total_ave_status = data.groupby("sale_status")["sale_amount"].agg(["sum", "mean", "median"])

#agg([]), is used to perform multple operations

In [128]:
total_ave_status

                      sum          mean    median
sale_status
Cancelled    1.262446e+07  33048.315550  32371.09
Completed    1.182973e+08  33389.033201  33198.04
Pending      3.397674e+07  31606.269674  29778.34

**Advance_Aggregations**

In [ ]:
data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
)

In [129]:

total_ave_sale_id = data.groupby("sale_rep_id")["sale_amount"].agg(["sum", "mean", "median"])

#agg([]), is used to perform multple operations

In [132]:
total_ave_sale_id.head(5)

                    sum          mean     median
sale_rep_id
1            8793624.75  32934.924157  32735.490
2            8721864.31  32788.963571  32971.875
3            7483168.82  33556.810852  32385.020
4            7473215.23  32073.885107  31932.040
5            7814744.92  32426.327469  31651.090

In [134]:
#if we want to rename sum, mean, median columns
rename = {
    "total_sales" : "sum",
    "average_sale": "mean",
    "median_sales" :"median"
}

total = data.groupby("car_model")["sale_amount"].agg(**rename)

`OR`

In [ ]:
#if we want to rename sum, mean, median columns
#simpler
total = data.groupby("car_model")["sale_amount"].agg(total_sales= "sum", average_sale= "mean",  median_sales = "median")

`or`

In [150]:
total = data.groupby("car_model").agg(
    total_sales= ("sale_amount", "sum"),
    average_sale= ("sale_amount","mean"),  
    median_sales = ("sale_amount", "median")
)

In [151]:
total

            total_sales  average_sale  median_sales
car_model
Camry       23515068.85  27470.874825     27448.575
Corolla     18559680.22  22442.176808     22477.280
Highlander  32562337.53  40002.871658     39988.890
RAV4        26647722.94  30985.724349     30922.640
Tacoma      28908731.32  34998.464068     34989.815
Tundra      34705000.21  42478.580428     42306.670

In [147]:
data.groupby("sale_status").agg({"sale_amount": "min", "commission_pct": "count"})

             sale_amount  commission_pct
sale_status
Cancelled       20139.53             281
Completed       20001.20            2671
Pending         20000.94             774

---

# Custom Aggregation function

In [1]:
import pandas as pd
data= pd.read_csv("Data/car_sales/toyota_sales_data.csv")

In [ ]:
#function
def calculate_range(series):
    return series.max() - series.min()

custom_aggegation = data.groupby("sale_rep_id")["sale_amount"]. \
    agg(
        total_sale = "sum",
        sales_min = "min",
        sales_max= "max",
        sales_range =calculate_range
    )

In [9]:
custom_aggegation.head(5)

             total_sale  sales_min  sales_max  sales_range
sale_rep_id
1            8793624.75   20218.81   49896.99     29678.18
2            8721864.31   20003.27   49193.79     29190.52
3            7483168.82   20254.97   49974.88     29719.91
4            7473215.23   20106.29   49907.66     29801.37
5            7814744.92   20131.62   49810.29     29678.67

In [11]:
car_model_aggegation = data.groupby("sale_rep_id"). \
    agg(
        total_sale = ( "sale_amount", "sum"),
        sales_count = ("sale_id","count"),
        sales_range =("sale_amount", calculate_range)
    )

In [13]:
car_model_aggegation.head(5)

             total_sale  sales_count  sales_range
sale_rep_id
1            8793624.75          267     29678.18
2            8721864.31          266     29190.52
3            7483168.82          223     29719.91
4            7473215.23          233     29801.37
5            7814744.92          241     29678.67

**Use Case:- calculate the percentage of completed sales for each sale_rep_id**

In [14]:
data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
)

In [21]:
def completed_sales_percentage(sales_status_series):
    total_sales = len(sales_status_series)
    completed_sales = (sales_status_series == "Completed").sum()
    return (completed_sales/total_sales) * 100

In [ ]:
#test per person (rep_id =8)
completed_sales_percentage(sale_of_8["sale_status"])

np.float64(70.15503875968993)

In [24]:
data.groupby('sale_rep_id')["sale_status"]. \
agg(
    total_sales = "count",
    completed_percentage = completed_sales_percentage
)

             total_sales  completed_percentage
sale_rep_id
1                    267             66.666667
2                    266             78.195489
3                    223             67.264574
4                    233             70.386266
5                    241             72.199170
6                    240             77.916667
7                    265             69.433962
8                    258             70.155039
9                    263             69.961977
10                   234             70.512821
11                   245             68.571429
12                   254             72.047244
13                   240             67.500000
14                   246             67.886179
15                   250             72.400000
16                   254             72.047244
17                   251             72.509960
18                   266             66.541353
19                   269             70.631970
20                   235             74.468085

**Use Case:- total sales and percentage per person**

In [25]:
data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
)

In [40]:
def custom_percentage_calculator(data_series):
    total_sales = len(data_series)
    completed_sale = (data_series == "Completed").sum()
    return (completed_sale/total_sales) *100

In [43]:
data.groupby("sale_rep_id"). \
    agg(
        total_sale = ("sale_amount","sum"),
        count_sales = ("sale_rep_id", "count"),
        completes_total = ("sale_status", custom_percentage_calculator)
    )

             total_sale  count_sales  completes_total
sale_rep_id
1            8793624.75          267        66.666667
2            8721864.31          266        78.195489
3            7483168.82          223        67.264574
4            7473215.23          233        70.386266
5            7814744.92          241        72.199170
6            8089256.01          240        77.916667
7            8658437.14          265        69.433962
8            8672081.85          258        70.155039
9            8623533.39          263        69.961977
10           7822524.30          234        70.512821
11           7946648.50          245        68.571429
12           8493429.13          254        72.047244
13           8012200.98          240        67.500000
14           8268540.28          246        67.886179
15           8218385.64          250        72.400000
16           8161330.01          254        72.047244
17           8247398.75          251        72.509960
18           8759602.34          266        66.541353
19           8788981.01          269        70.631970
20           7849573.71          235        74.468085

---

# Custome Aggeragtion Function 2

**apply()** → use a function on each value, row, or column to perform custom calculations/logic.

data.apply(my_function, axis=1)

In [18]:
import pandas as pd


data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
    )

In [19]:
data["commission_pct"].isnull().sum()

np.int64(1274)

In [20]:
data.fillna({"commission_pct": 0}, inplace=True)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,0.00,Cancelled

In [21]:
data["commission_pct"].isnull().sum()

np.int64(0)

In [22]:
def calculate_commison(sale):
    
    return sale["sale_amount"] * sale["commission_pct"]

In [23]:
data.apply(calculate_commison, axis=1)

0       2224.8440
1          0.0000
2          0.0000
3          0.0000
4       1494.3597
          ...
4995    1074.2415
4996    1325.9620
4997     615.6078
4998       0.0000
4999       0.0000
Length: 5000, dtype: float64

`OR`

In [24]:
#without function, works seperaty
data.apply(lambda sale : sale["sale_amount"] * sale["commission_pct"], axis = 1)

0       2224.8440
1          0.0000
2          0.0000
3          0.0000
4       1494.3597
          ...
4995    1074.2415
4996    1325.9620
4997     615.6078
4998       0.0000
4999       0.0000
Length: 5000, dtype: float64

`OR`

We can just remove the null directly inside the function

In [ ]:
#removing null directly
def calculate_commison_11(sale):
    commission_pct = sale["commission_pct"] if pd.notnull(sale["commission_pct"]) else 0
    return round(sale["sale_amount"] * commission_pct, 2)

In [26]:
data.apply(calculate_commison_11, axis=1)

0       2224.84
1          0.00
2          0.00
3          0.00
4       1494.36
         ...
4995    1074.24
4996    1325.96
4997     615.61
4998       0.00
4999       0.00
Length: 5000, dtype: float64

**Use Case :If the tottal_commison is greater than 100, return True**

In [27]:
data["commision_amount"] = data.apply(calculate_commison_11, axis=1)

In [28]:
data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commision_amount
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,0.00,Pending,0.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.36

In [29]:
#there are too many unwanted header, so droping it

data = data.drop(["sale_date","sale_date"], axis=1)

In [30]:
def flag_high_comminsion(sale):
    return sale["commision_amount"] >1000

In [31]:
data.apply(flag_high_comminsion,axis=1)

0        True
1       False
2       False
3       False
4        True
        ...
4995     True
4996     True
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [33]:
#update it to the actual data
data["High_commision"]=data.apply(flag_high_comminsion,axis=1)

In [35]:
data.head(5)

,sale_id,sale_rep_id,car_model,sale_amount,commission_pct,sale_status,commision_amount,High_commision
0,1,16,Tundra,44496.88,0.05,Completed,2224.84,True
1,2,11,Tacoma,34824.72,0.00,Pending,0.00,False
2,3,5,Corolla,20275.08,0.00,Completed,0.00,False
3,4,20,Corolla,20068.93,0.00,Completed,0.00,False
4,5,1,Tundra,49811.99,0.03,Completed,1494.36,True

---

# Add New Columns to pandas Dataframe

In [101]:
import pandas as pd


toyota_data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
    )

In [103]:
toyota_data["commission_pct"] = toyota_data["commission_pct"].fillna(0)

In [ ]:
# total commission_amount
toyota_data["commission_amount"] = toyota_data["sale_amount"] * toyota_data["commission_pct"]

In [106]:
#Creating a new column and setting as Low as default
toyota_data["sale_category"] = "Low"

In [107]:

toyota_data.loc[toyota_data["sale_amount"] > 30000, "sale_category" ] = "Medium"

In [110]:
toyota_data.loc[toyota_data["sale_amount"] > 40000, "sale_category" ] = "High"

In [109]:
toyota_data = toyota_data.drop(["sale_rep_id", "sale_status"], axis=1)

In [111]:
toyota_data.head(20)

,sale_id,sale_date,car_model,sale_amount,commission_pct,commission_amount,sale_category
0,1,2024-11-18,Tundra,44496.88,0.05,2224.8440,High
1,2,2024-11-08,Tacoma,34824.72,0.00,0.0000,Medium
2,3,2024-11-03,Corolla,20275.08,0.00,0.0000,Low
3,4,2024-11-06,Corolla,20068.93,0.00,0.0000,Low
4,5,2024-11-26,Tundra,49811.99,0.03,1494.3597,High
5,6,2024-11-28,RAV4,34346.20,0.03,1030.3860,Medium
6,7,2024-11-30,RAV4,33073.24,0.03,992.1972,Medium
7,8,2024-11-05,Camry,25561.86,0.00,0.0000,Low
8,9,2024-11-25,RAV4,29690.54,0.03,890.7162,Low
9,10,2024-11-09,Camry,27321.71,0.03,819.6513,Low
10,11,2024-11-11,Highlander,40044.87,0.02,800.8974,High
11,12,2024-11-23,Tundra,39427.38,0.05,1971.3690,Medium
12,13,2024-11-08,Tundra,38598.58,0.02,771.9716,Medium
13,14,2024-11-20,Tacoma,33043.74,0.02,660.8748,Medium
14,15,2024-11-14,RAV4,28455.43,0.02,569.1086,Low
15,16,2024-11-10,Corolla,24909.11,0.03,747.2733,Low
16,17,2024-11-18,Camry,26676.29,0.00,0.0000,Low
17,18,2024-11-02,RAV4,32751.81,0.00,0.0000,Medium
18,19,2024-11-26,RAV4,28992.27,0.00,0.0000,Low
19,20,2024-11-10,Tacoma,35503.75,0.03,1065.1125,Medium

`Using Apply() Method`

In [128]:
def category(sale):
    sale["sale_category"] = "Low"

    if sale["sale_amount"] > 30000:
        sale["sale_category"] = "medium"

    if sale["sale_amount"] > 40000:
            sale["sale_category"] = "High"

    return sale["sale_category"]

`OR`

In [ ]:
def category(sale):
    if sale["sale_amount"] > 40000:
        return "High"

    elif sale["sale_amount"] > 30000:
        return  "Midium"

    else:
        return "Low"

In [129]:
toyota_data["sale_category"]=toyota_data.apply(category, axis=1)

In [130]:
toyota_data.head(10)

,sale_id,sale_date,car_model,sale_amount,commission_pct,commission_amount,sale_category
0,1,2024-11-18,Tundra,44496.88,0.05,2224.8440,High
1,2,2024-11-08,Tacoma,34824.72,0.00,0.0000,medium
2,3,2024-11-03,Corolla,20275.08,0.00,0.0000,Low
3,4,2024-11-06,Corolla,20068.93,0.00,0.0000,Low
4,5,2024-11-26,Tundra,49811.99,0.03,1494.3597,High
5,6,2024-11-28,RAV4,34346.20,0.03,1030.3860,medium
6,7,2024-11-30,RAV4,33073.24,0.03,992.1972,medium
7,8,2024-11-05,Camry,25561.86,0.00,0.0000,Low
8,9,2024-11-25,RAV4,29690.54,0.03,890.7162,Low
9,10,2024-11-09,Camry,27321.71,0.03,819.6513,Low

In [ ]:
def category(sale):
    if sale["sale_amount"] > 40000:
        return "High"

    elif sale["sale_amount"] > 30000:
        return  "Midium"

    else:
        return "Low"

**Use Case: Update "Pending" Status to "In Progress"**

In [61]:
import pandas as pd


toyota_data= pd.read_csv(
    "Data/car_sales/toyota_sales_data.csv"
    )

In [62]:
toyota_data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

In [63]:
toyota_data["sale_status"] = toyota_data["sale_status"]. replace("Pending", "In Progress")

In [64]:
toyota_data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,In Progress
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed

**Use Case: Calculate profit_margin and set the sale_category very high for more than 45000**

In [ ]:
#Filling Null Value
toyota_data["commission_pct"] = toyota_data["commission_pct"]. fillna(0)

In [ ]:
#Calculating  total_commission
toyota_data["total_commission"] = toyota_data["commission_pct"] * toyota_data["sale_amount"]

In [ ]:
#Calculating  profit_margin
toyota_data["profit_margin"] = (toyota_data["sale_amount"] - toyota_data["total_commission"]) / toyota_data["sale_amount"]

In [68]:
toyota_data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,total_commission,profit_margin
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.8440,0.95
1,2,11,2024-11-08,Tacoma,34824.72,0.00,In Progress,0.0000,1.00
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,0.0000,1.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,0.0000,1.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.3597,0.97

In [69]:
def category(sale):
    if sale["sale_amount"] > 45000:
            return "Very High"
    if sale["sale_amount"] > 40000:
        return "High"

    elif sale["sale_amount"] > 30000:
        return  "Midium"

    else:
        return "Low"

In [70]:
toyota_data["sale_category"] = toyota_data.apply(category, axis=1)

In [71]:
toyota_data.head(5)

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,total_commission,profit_margin,sale_category
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.8440,0.95,High
1,2,11,2024-11-08,Tacoma,34824.72,0.00,In Progress,0.0000,1.00,Midium
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,0.0000,1.00,Low
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,0.0000,1.00,Low
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.3597,0.97,Very High

---

# Chaining  Transformation

Chaining transformations means performing multiple DataFrame operations one after another in a single chain, instead of creating many intermediate variables.

* Efficiency → fewer unnecessary steps/variables
* Readability → transformations are easy to follow
* Scalability → easier to add or modify transformations

**Use Case:- Calculate Commission Earned for Completed Sales**

In [75]:
import pandas as pd


toyota_sales_data= pd.read_csv("Data/car_sales/toyota_sales_data.csv")
sales_reps_data= pd.read_csv("Data/car_sales/sales_reps_data.csv")

In [ ]:
# Normal_1 method
completed_sales = toyota_sales_data[toyota_sales_data["sale_status"] == "Completed"]

In [ ]:
# Normal_2 method
completed_sales["commission_earned"] = (
    completed_sales["sale_amount"] * completed_sales["commission_pct"]
)

`Or`

In [76]:
#Using Chaining  Transformation
sales_with_commission = (
    toyota_sales_data[toyota_sales_data["sale_status"] == "Completed"]
    .assign(
        commission_earned=lambda x:
            x["sale_amount"] * x["commission_pct"]
    )
)

In [77]:
sales_with_commission

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commission_earned
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.8440
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed,NaN
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed,NaN
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.3597
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed,1030.3860
...,...,...,...,...,...,...,...,...
4992,4993,10,2024-11-26,Tundra,47497.87,0.02,Completed,949.9574
4993,4994,4,2024-11-07,Camry,26498.13,0.05,Completed,1324.9065
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed,1074.2415
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed,615.6078
4998,4999,10,2024-11-21,Corolla,22654.59,NaN,Completed,NaN

`OR`

**Chaining Transformation using Multiple Datasets**

In [87]:
sales_with_commission = (
    pd.merge(
        sales_reps_data,
        toyota_sales_data,
        
        left_on= "rep_id",
        right_on="sale_rep_id",
        how= "inner"
    )

    .query("sale_status == 'Completed'") \
    .assign(commision_earned = lambda x : x["sale_amount"] * x["commission_pct"])
)

In [88]:
sales_with_commission

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commision_earned
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.3597
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,NaN,Completed,NaN
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed,1031.1995
5,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,98,1,2024-11-07,Tacoma,31378.09,0.02,Completed,627.5618
6,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,99,1,2024-11-04,Tundra,39879.41,0.02,Completed,797.5882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,NaN,Completed,NaN
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed,804.9138
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed,1764.6785
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed,630.8672
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,NaN,Completed,NaN

---

# Advance Chaining Transformation

**Real World Example**

In [1]:
import pandas as pd


toyota_sales_data= pd.read_csv("Data/car_sales/toyota_sales_data.csv")
sales_reps_data= pd.read_csv("Data/car_sales/sales_reps_data.csv")

In [2]:
sales_with_commission = (
    toyota_sales_data.fillna({"commission_pct" : 0})
    .query("sale_status == 'Completed'")
    .assign(
        commision_earned = lambda x: 
        round(x["sale_amount"] * x["commission_pct"], 2)
        )
)

In [3]:
sales_with_commission

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commision_earned
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.84
2,3,5,2024-11-03,Corolla,20275.08,0.00,Completed,0.00
3,4,20,2024-11-06,Corolla,20068.93,0.00,Completed,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.36
5,6,14,2024-11-28,RAV4,34346.20,0.03,Completed,1030.39
...,...,...,...,...,...,...,...,...
4992,4993,10,2024-11-26,Tundra,47497.87,0.02,Completed,949.96
4993,4994,4,2024-11-07,Camry,26498.13,0.05,Completed,1324.91
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed,1074.24
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed,615.61
4998,4999,10,2024-11-21,Corolla,22654.59,0.00,Completed,0.00

In [4]:
#Using multiple Dataset
pd.merge(
        sales_reps_data,
        toyota_sales_data,
        left_on= "rep_id",
        right_on="sale_rep_id",
        how= "inner"
    ).fillna({"commission_pct" : 0}) \
    .query("sale_status == 'Completed'") \
    .assign(
        commision_earned = lambda x: 
        round(x["sale_amount"] * x["commission_pct"], 2)
        )

,rep_id,first_name,last_name,email,phone_number,hire_date,region,status,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commision_earned
0,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.36
3,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,24,1,2024-11-03,Corolla,24278.39,0.00,Completed,0.00
4,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,25,1,2024-11-21,Corolla,20623.99,0.05,Completed,1031.20
5,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,98,1,2024-11-07,Tacoma,31378.09,0.02,Completed,627.56
6,1,Anthony,Davis,anthony.davis@toyota.com,-5390,7/21/22,North,Active,99,1,2024-11-04,Tundra,39879.41,0.02,Completed,797.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4951,20,2024-11-16,Camry,25686.30,0.00,Completed,0.00
4996,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4958,20,2024-11-08,Camry,26830.46,0.03,Completed,804.91
4997,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4973,20,2024-11-12,Highlander,35293.57,0.05,Completed,1764.68
4998,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4989,20,2024-11-04,RAV4,31543.36,0.02,Completed,630.87
4999,20,Edward,Jones,edward.jones@toyota.com,-4686,7/9/20,North,Inactive,4991,20,2024-11-17,Highlander,36500.60,0.00,Completed,0.00

In [6]:
#using Group by
#Using multiple Dataset
result= (
    pd.merge(
        sales_reps_data,
        toyota_sales_data,
        left_on= "rep_id",
        right_on="sale_rep_id",
        how= "inner"
    )
    .fillna({"commission_pct" : 0})
    .query("sale_status == 'Completed'")
    .assign(
        commission_earned = lambda x: 
            round(x["sale_amount"] * x["commission_pct"], 2)
    )
    .groupby("region")
    .agg(
        total_sales = ("sale_amount", "sum"),
        avg_commission = ("commission_earned","mean")
    )
    .reset_index()
)

In [7]:
result

  region  total_sales  avg_commission
0   East  23801097.84      841.740521
1  North  59489910.74      847.423491
2  South  11024201.99      870.607674
3   West  23982134.06      842.778313

**Best practice: use () for multi-line chaining**

result = (

    pd.merge(...)

    .fillna(...)

    .query(...)

    .assign(...)

    .groupby(...)

    .agg(...)

    .reset_index()
    
)

---

# Complete Workflow

**Monthly Sales Commision**

In [ ]:
import pandas as pd

toyota_sales_data= pd.read_csv("Data/car_sales/toyota_sales_data.csv")
sales_reps_data= pd.read_csv("Data/car_sales/sales_reps_data.csv")

In [ ]:
monthly_summary = (
    pd.merge(
        sales_reps_data,
        toyota_sales_data,
        left_on= "rep_id",
        right_on="sale_rep_id", 
        how= "inner"
    )
    .fillna({"commission_pct": 0})
    .assign(total_commission = lambda x : round(x["sale_amount"] * x["commission_pct"]))
    .assign(sale_month = lambda x: pd.to_datetime(x["sale_date"]).dt.to_period("M")) #to display only months to calculate Total sales for each month
    .groupby(["sale_month", "rep_id", "first_name", "last_name", "email"])
    .agg(
        total_amount = ("sale_amount","sum"),
        total_commision = ("total_commission", "sum")
    )
    .reset_index()


)

In [41]:
monthly_summary

,sale_month,rep_id,first_name,last_name,email,total_amount,total_commision
0,2024-11,1,Anthony,Davis,anthony.davis@toyota.com,8793624.75,229835.0
1,2024-11,2,Edward,Smith,edward.smith@toyota.com,8721864.31,218995.0
2,2024-11,3,Paul,Jones,paul.jones@toyota.com,7483168.82,184880.0
3,2024-11,4,Robert,Lopez,robert.lopez@toyota.com,7473215.23,191386.0
4,2024-11,5,Steven,Wilson,steven.wilson@toyota.com,7814744.92,216161.0
5,2024-11,6,Brian,Martinez,brian.martinez@toyota.com,8089256.01,189754.0
6,2024-11,7,Christopher,Jones,christopher.jones@toyota.com,8658437.14,202114.0
7,2024-11,8,David,Davis,david.davis@toyota.com,8672081.85,222119.0
8,2024-11,9,Thomas,Smith,thomas.smith@toyota.com,8623533.39,211728.0
9,2024-11,10,Christopher,Brown,christopher.brown@toyota.com,7822524.30,188086.0
10,2024-11,11,David,Gonzalez,david.gonzalez@toyota.com,7946648.50,190773.0
11,2024-11,12,Daniel,Jackson,daniel.jackson@toyota.com,8493429.13,219825.0
12,2024-11,13,Robert,Hernandez,robert.hernandez@toyota.com,8012200.98,208535.0
13,2024-11,14,Daniel,Williams,daniel.williams@toyota.com,8268540.28,208778.0
14,2024-11,15,William,Moore,william.moore@toyota.com,8218385.64,207620.0
15,2024-11,16,Michael,Martinez,michael.martinez@toyota.com,8161330.01,216682.0
16,2024-11,17,Charles,Lopez,charles.lopez@toyota.com,8247398.75,200372.0
17,2024-11,18,Daniel,Martinez,daniel.martinez@toyota.com,8759602.34,220996.0
18,2024-11,19,Thomas,Wilson,thomas.wilson@toyota.com,8788981.01,224914.0
19,2024-11,20,Edward,Jones,edward.jones@toyota.com,7849573.71,193408.0

In [43]:
#write to CSV
monthly_summary.to_csv("data/car_sales/monthly_sales_commision.csv", index=False) # "index=False" to remove the index

In [ ]:
50